(define (problem roverprob0) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 rover1 - Rover
	rover0store rover1store - Store
	waypoint0 waypoint1 waypoint2 waypoint3 - Waypoint
	camera0 camera1 camera2 - Camera
	objective0 objective1 - Objective
	)
(:init
	(visible waypoint0 waypoint1)
	(visible waypoint1 waypoint0)
	(visible waypoint1 waypoint2)
	(visible waypoint2 waypoint1)
	(visible waypoint1 waypoint3)
	(visible waypoint3 waypoint1)
	(visible waypoint2 waypoint0)
	(visible waypoint0 waypoint2)
	(visible waypoint2 waypoint3)
	(visible waypoint3 waypoint2)
	(visible waypoint3 waypoint0)
	(visible waypoint0 waypoint3)
	(at_soil_sample waypoint0)
	(= (power_loss_rate waypoint0) 1.62)
	(= (power_at_station waypoint0) 0)
	(= (power_capacity waypoint0) 108)
	(at_soil_sample waypoint1)
	(= (power_loss_rate waypoint1) 1.76)
	(= (power_at_station waypoint1) 61)
	(= (power_capacity waypoint1) 138)
	(= (power_loss_rate waypoint2) 1.87)
	(= (power_at_station waypoint2) 12)
	(= (power_capacity waypoint2) 145)
	(at_rock_sample waypoint3)
	(= (power_loss_rate waypoint3) 1.56)
	(= (power_at_station waypoint3) 40)
	(= (power_capacity waypoint3) 137)
	(at_lander general waypoint1)
	(channel_free general)
	(= (energy rover0) 40)
	(= (energy_capacity rover0) 94)
	(at rover0 waypoint0)
	(available rover0)
	(store_of rover0store rover0)
	(empty rover0store)
	(equipped_for_soil_analysis rover0)
	(equipped_for_rock_analysis rover0)
	(equipped_for_imaging rover0)
	(can_traverse rover0 waypoint0 waypoint1)
	(can_traverse rover0 waypoint1 waypoint0)
	(can_traverse rover0 waypoint0 waypoint2)
	(can_traverse rover0 waypoint2 waypoint0)
	(can_traverse rover0 waypoint0 waypoint3)
	(can_traverse rover0 waypoint3 waypoint0)
	(= (energy rover1) 48)
	(= (energy_capacity rover1) 84)
	(at rover1 waypoint0)
	(available rover1)
	(store_of rover1store rover1)
	(empty rover1store)
	(equipped_for_soil_analysis rover1)
	(equipped_for_imaging rover1)
	(can_traverse rover1 waypoint0 waypoint1)
	(can_traverse rover1 waypoint1 waypoint0)
	(can_traverse rover1 waypoint0 waypoint2)
	(can_traverse rover1 waypoint2 waypoint0)
	(can_traverse rover1 waypoint0 waypoint3)
	(can_traverse rover1 waypoint3 waypoint0)
	(on_board camera0 rover1)
	(calibration_target camera0 objective1)
	(supports camera0 low_res)
	(on_board camera1 rover0)
	(calibration_target camera1 objective0)
	(supports camera1 colour)
	(on_board camera2 rover0)
	(calibration_target camera2 objective1)
	(supports camera2 high_res)
	(supports camera2 low_res)
	(visible_from objective0 waypoint0)
	(visible_from objective0 waypoint1)
	(visible_from objective1 waypoint0)
	(visible_from objective1 waypoint1)
)

(:goal (and
(communicated_soil_data waypoint1)
(communicated_soil_data waypoint0)
(communicated_rock_data waypoint3)
(communicated_image_data objective1 low_res)
(communicated_image_data objective0 low_res)
	)
)

(:metric minimize (total-time))
)
