(define (problem roverprob0) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 - Rover
	rover0store - Store
	waypoint0 waypoint1 waypoint2 - Waypoint
	camera0 camera1 - Camera
	objective0 objective1 - Objective
	)
(:init
	(visible waypoint0 waypoint1)
	(visible waypoint1 waypoint0)
	(visible waypoint0 waypoint2)
	(visible waypoint2 waypoint0)
	(visible waypoint2 waypoint1)
	(visible waypoint1 waypoint2)
	(at_soil_sample waypoint0)
	(= (power_loss_rate waypoint0) 1.44)
	(= (power_at_station waypoint0) 53)
	(= (power_capacity waypoint0) 178)
	(at_soil_sample waypoint1)
	(at_rock_sample waypoint1)
	(= (power_loss_rate waypoint1) 1.55)
	(= (power_at_station waypoint1) 76)
	(= (power_capacity waypoint1) 104)
	(at_soil_sample waypoint2)
	(at_rock_sample waypoint2)
	(= (power_loss_rate waypoint2) 1.13)
	(= (power_at_station waypoint2) 41)
	(= (power_capacity waypoint2) 188)
	(at_lander general waypoint2)
	(channel_free general)
	(= (energy rover0) 34)
	(= (energy_capacity rover0) 84)
	(at rover0 waypoint2)
	(available rover0)
	(store_of rover0store rover0)
	(empty rover0store)
	(equipped_for_soil_analysis rover0)
	(equipped_for_imaging rover0)
	(can_traverse rover0 waypoint2 waypoint0)
	(can_traverse rover0 waypoint0 waypoint2)
	(can_traverse rover0 waypoint2 waypoint1)
	(can_traverse rover0 waypoint1 waypoint2)
	(on_board camera0 rover0)
	(calibration_target camera0 objective0)
	(supports camera0 colour)
	(on_board camera1 rover0)
	(calibration_target camera1 objective1)
	(supports camera1 colour)
	(supports camera1 high_res)
	(supports camera1 low_res)
	(visible_from objective0 waypoint0)
	(visible_from objective0 waypoint1)
	(visible_from objective0 waypoint2)
	(visible_from objective1 waypoint0)
	(visible_from objective1 waypoint1)
	(visible_from objective1 waypoint2)
)

(:goal (and
(communicated_soil_data waypoint1)
(communicated_image_data objective1 high_res)
	)
)

(:metric minimize (total-time))
)
