(define (problem procurement0) (:domain procurement)
(:objects
	A - itemA B - itemB C - itemC D - itemD E - itemE F - itemF
	G - itemG H - itemH I - itemI J - itemJ K - itemK L - itemL
	M - itemM N - itemN O - itemO P - itemP Q - itemQ R - itemR
	S - itemS

	workshop0 workshop1 workshop2  - workshop
	supplier0 supplier1 supplier2  - supplier
	customer0 customer1 customer2  - customer
	)

(:init
	(at workshop1)
	(available)

	(= (stock A) 0)
	(= (stock B) 0)
	(= (stock C) 0)
	(= (stock F) 0)
	(= (stock H) 0)
	(= (stock K) 0)
	(= (stock L) 0)
	(= (stock M) 0)
	(= (stock D) 0)
	(= (stock E) 0)
	(= (stock G) 0)
	(= (stock I) 0)
	(= (stock J) 0)
	(= (stock N) 0)
	(= (stock O) 0)
	(= (stock Q) 0)
	(= (stock R) 0)
	(= (stock P) 0)
	(= (stock S) 0)

	(= (item-goal A) 11)
	(= (item-goal B) 10)
	(= (item-goal C) 9)
	(= (item-goal F) 7)
	(= (item-goal H) 11)
	(= (item-goal K) 8)
	(= (item-goal L) 7)
	(= (item-goal M) 10)
	(= (item-goal D) 10)
	(= (item-goal E) 11)
	(= (item-goal G) 10)
	(= (item-goal I) 7)
	(= (item-goal J) 8)
	(= (item-goal N) 10)
	(= (item-goal O) 7)
	(= (item-goal Q) 7)
	(= (item-goal R) 7)
	(= (item-goal P) 8)
	(= (item-goal S) 10)

	(can_produce_A workshop0)
	(can_produce_B workshop0)
	(can_produce_C workshop2)
	(can_produce_F workshop0)
	(can_produce_H workshop2)
	(can_produce_K workshop2)
	(can_produce_L workshop2)
	(can_produce_M workshop2)

	(can_supply_D supplier0)
	(can_supply_E supplier0)
	(can_supply_G supplier2)
	(can_supply_I supplier0)
	(can_supply_J supplier1)
	(can_supply_N supplier1)
	(can_supply_O supplier1)
	(can_supply_Q supplier0)
	(can_supply_R supplier2)
	(can_supply_P supplier2)
	(can_supply_S supplier2)

	(link workshop0 workshop1 )
	(link workshop0 workshop2 )
	(link workshop0 supplier0 )
	(link workshop0 supplier1 )
	(link workshop0 supplier2 )
	(link workshop0 customer0 )
	(link workshop0 customer1 )
	(link workshop0 customer2 )
	(link workshop1 workshop0 )
	(link workshop1 workshop2 )
	(link workshop1 supplier0 )
	(link workshop1 supplier1 )
	(link workshop1 supplier2 )
	(link workshop1 customer0 )
	(link workshop1 customer1 )
	(link workshop1 customer2 )
	(link workshop2 workshop0 )
	(link workshop2 workshop1 )
	(link workshop2 supplier0 )
	(link workshop2 supplier1 )
	(link workshop2 supplier2 )
	(link workshop2 customer0 )
	(link workshop2 customer1 )
	(link workshop2 customer2 )
	(link supplier0 workshop0 )
	(link supplier0 workshop1 )
	(link supplier0 workshop2 )
	(link supplier0 supplier1 )
	(link supplier0 supplier2 )
	(link supplier0 customer0 )
	(link supplier0 customer1 )
	(link supplier0 customer2 )
	(link supplier1 workshop0 )
	(link supplier1 workshop1 )
	(link supplier1 workshop2 )
	(link supplier1 supplier0 )
	(link supplier1 supplier2 )
	(link supplier1 customer0 )
	(link supplier1 customer1 )
	(link supplier1 customer2 )
	(link supplier2 workshop0 )
	(link supplier2 workshop1 )
	(link supplier2 workshop2 )
	(link supplier2 supplier0 )
	(link supplier2 supplier1 )
	(link supplier2 customer0 )
	(link supplier2 customer1 )
	(link supplier2 customer2 )
	(link customer0 workshop0 )
	(link customer0 workshop1 )
	(link customer0 workshop2 )
	(link customer0 supplier0 )
	(link customer0 supplier1 )
	(link customer0 supplier2 )
	(link customer0 customer1 )
	(link customer0 customer2 )
	(link customer1 workshop0 )
	(link customer1 workshop1 )
	(link customer1 workshop2 )
	(link customer1 supplier0 )
	(link customer1 supplier1 )
	(link customer1 supplier2 )
	(link customer1 customer0 )
	(link customer1 customer2 )
	(link customer2 workshop0 )
	(link customer2 workshop1 )
	(link customer2 workshop2 )
	(link customer2 supplier0 )
	(link customer2 supplier1 )
	(link customer2 supplier2 )
	(link customer2 customer0 )
	(link customer2 customer1 )
)

(:goal	(and

	(delivered K customer0)
		)
	)
(:metric minimize (total-time) )
)