(define (problem procurement0) (:domain procurement)
(:objects
	A - itemA B - itemB C - itemC D - itemD E - itemE F - itemF
	G - itemG H - itemH I - itemI J - itemJ K - itemK L - itemL
	M - itemM N - itemN O - itemO P - itemP Q - itemQ R - itemR
	S - itemS

	workshop0 workshop1 workshop2 workshop3  - workshop
	supplier0 supplier1 supplier2 supplier3  - supplier
	customer0 customer1 customer2 customer3  - customer
	)

(:init
	(at workshop1)
	(available)

	(= (stock A) 0)
	(= (stock B) 0)
	(= (stock C) 0)
	(= (stock F) 0)
	(= (stock H) 0)
	(= (stock K) 0)
	(= (stock L) 0)
	(= (stock M) 0)
	(= (stock D) 0)
	(= (stock E) 0)
	(= (stock G) 0)
	(= (stock I) 0)
	(= (stock J) 0)
	(= (stock N) 0)
	(= (stock O) 0)
	(= (stock Q) 0)
	(= (stock R) 0)
	(= (stock P) 0)
	(= (stock S) 0)

	(= (item-goal A) 11)
	(= (item-goal B) 11)
	(= (item-goal C) 11)
	(= (item-goal F) 11)
	(= (item-goal H) 9)
	(= (item-goal K) 11)
	(= (item-goal L) 9)
	(= (item-goal M) 11)
	(= (item-goal D) 9)
	(= (item-goal E) 11)
	(= (item-goal G) 10)
	(= (item-goal I) 8)
	(= (item-goal J) 8)
	(= (item-goal N) 11)
	(= (item-goal O) 8)
	(= (item-goal Q) 7)
	(= (item-goal R) 9)
	(= (item-goal P) 10)
	(= (item-goal S) 7)

	(can_produce_A workshop0)
	(can_produce_B workshop0)
	(can_produce_C workshop1)
	(can_produce_F workshop2)
	(can_produce_H workshop1)
	(can_produce_K workshop3)
	(can_produce_L workshop3)
	(can_produce_M workshop3)

	(can_supply_D supplier3)
	(can_supply_E supplier3)
	(can_supply_G supplier1)
	(can_supply_I supplier3)
	(can_supply_J supplier0)
	(can_supply_N supplier1)
	(can_supply_O supplier3)
	(can_supply_Q supplier3)
	(can_supply_R supplier1)
	(can_supply_P supplier0)
	(can_supply_S supplier2)

	(link workshop0 workshop1 )
	(link workshop0 workshop2 )
	(link workshop0 workshop3 )
	(link workshop0 supplier0 )
	(link workshop0 supplier1 )
	(link workshop0 supplier2 )
	(link workshop0 supplier3 )
	(link workshop0 customer0 )
	(link workshop0 customer1 )
	(link workshop0 customer2 )
	(link workshop0 customer3 )
	(link workshop1 workshop0 )
	(link workshop1 workshop2 )
	(link workshop1 workshop3 )
	(link workshop1 supplier0 )
	(link workshop1 supplier1 )
	(link workshop1 supplier2 )
	(link workshop1 supplier3 )
	(link workshop1 customer0 )
	(link workshop1 customer1 )
	(link workshop1 customer2 )
	(link workshop1 customer3 )
	(link workshop2 workshop0 )
	(link workshop2 workshop1 )
	(link workshop2 workshop3 )
	(link workshop2 supplier0 )
	(link workshop2 supplier1 )
	(link workshop2 supplier2 )
	(link workshop2 supplier3 )
	(link workshop2 customer0 )
	(link workshop2 customer1 )
	(link workshop2 customer2 )
	(link workshop2 customer3 )
	(link workshop3 workshop0 )
	(link workshop3 workshop1 )
	(link workshop3 workshop2 )
	(link workshop3 supplier0 )
	(link workshop3 supplier1 )
	(link workshop3 supplier2 )
	(link workshop3 supplier3 )
	(link workshop3 customer0 )
	(link workshop3 customer1 )
	(link workshop3 customer2 )
	(link workshop3 customer3 )
	(link supplier0 workshop0 )
	(link supplier0 workshop1 )
	(link supplier0 workshop2 )
	(link supplier0 workshop3 )
	(link supplier0 supplier1 )
	(link supplier0 supplier2 )
	(link supplier0 supplier3 )
	(link supplier0 customer0 )
	(link supplier0 customer1 )
	(link supplier0 customer2 )
	(link supplier0 customer3 )
	(link supplier1 workshop0 )
	(link supplier1 workshop1 )
	(link supplier1 workshop2 )
	(link supplier1 workshop3 )
	(link supplier1 supplier0 )
	(link supplier1 supplier2 )
	(link supplier1 supplier3 )
	(link supplier1 customer0 )
	(link supplier1 customer1 )
	(link supplier1 customer2 )
	(link supplier1 customer3 )
	(link supplier2 workshop0 )
	(link supplier2 workshop1 )
	(link supplier2 workshop2 )
	(link supplier2 workshop3 )
	(link supplier2 supplier0 )
	(link supplier2 supplier1 )
	(link supplier2 supplier3 )
	(link supplier2 customer0 )
	(link supplier2 customer1 )
	(link supplier2 customer2 )
	(link supplier2 customer3 )
	(link supplier3 workshop0 )
	(link supplier3 workshop1 )
	(link supplier3 workshop2 )
	(link supplier3 workshop3 )
	(link supplier3 supplier0 )
	(link supplier3 supplier1 )
	(link supplier3 supplier2 )
	(link supplier3 customer0 )
	(link supplier3 customer1 )
	(link supplier3 customer2 )
	(link supplier3 customer3 )
	(link customer0 workshop0 )
	(link customer0 workshop1 )
	(link customer0 workshop2 )
	(link customer0 workshop3 )
	(link customer0 supplier0 )
	(link customer0 supplier1 )
	(link customer0 supplier2 )
	(link customer0 supplier3 )
	(link customer0 customer1 )
	(link customer0 customer2 )
	(link customer0 customer3 )
	(link customer1 workshop0 )
	(link customer1 workshop1 )
	(link customer1 workshop2 )
	(link customer1 workshop3 )
	(link customer1 supplier0 )
	(link customer1 supplier1 )
	(link customer1 supplier2 )
	(link customer1 supplier3 )
	(link customer1 customer0 )
	(link customer1 customer2 )
	(link customer1 customer3 )
	(link customer2 workshop0 )
	(link customer2 workshop1 )
	(link customer2 workshop2 )
	(link customer2 workshop3 )
	(link customer2 supplier0 )
	(link customer2 supplier1 )
	(link customer2 supplier2 )
	(link customer2 supplier3 )
	(link customer2 customer0 )
	(link customer2 customer1 )
	(link customer2 customer3 )
	(link customer3 workshop0 )
	(link customer3 workshop1 )
	(link customer3 workshop2 )
	(link customer3 workshop3 )
	(link customer3 supplier0 )
	(link customer3 supplier1 )
	(link customer3 supplier2 )
	(link customer3 supplier3 )
	(link customer3 customer0 )
	(link customer3 customer1 )
	(link customer3 customer2 )
)

(:goal	(and

	(delivered C customer3)
		)
	)
(:metric minimize (total-time) )
)