(define (problem cashpoint0) (:domain cashpoint)
(:objects
	location0 location1 location2 location3 location4 location5  - shop
	bank0 bank1 bank2  - bank
	changeOffice0 changeOffice1 changeOffice2  - changeOffice
	item0 item1 item2 item3 item4 item5  - item
	currency0 currency1 currency2  - currency
)

(:init
	(at location2)(available)
	(canbuy location2 item0)
	(canbuy location2 item1)
	(canbuy location5 item2)
	(canbuy location1 item3)
	(canbuy location5 item4)
	(canbuy location1 item5)
	(= (currency_goal currency0) 248)
	(= (currency_goal currency1) 243)
	(= (currency_goal currency2) 222)
	(= (price item0) 5)
	(= (price item1) 38)
	(= (price item2) 63)
	(= (price item3) 65)
	(= (price item4) 38)
	(= (price item5) 99)
	(= (balance currency0) 1806)
	(= (balance currency1) 1795)
	(= (balance currency2) 708)
	(= (exchangeRate currency0 currency1) 1.22471)
	(= (exchangeRate currency0 currency2) 1.46449)
	(= (exchangeRate currency1 currency0) 0.816521)
	(= (exchangeRate currency1 currency2) 1.85397)
	(= (exchangeRate currency2 currency0) 0.682831)
	(= (exchangeRate currency2 currency1) 0.539383)
	(= (inpocket currency0) 54)
	(= (inpocket currency1) 25)
	(= (inpocket currency2) 189)
	(= (points currency0) 38)
	(= (points currency1) 39)
	(= (points currency2) 18)
	(= (bank-reserve bank0 currency0) 4052)
	(= (bank-reserve bank0 currency1) 4078)
	(= (bank-reserve bank0 currency2) 9302)
	(= (bank-reserve bank1 currency0) 9750)
	(= (bank-reserve bank1 currency1) 8964)
	(= (bank-reserve bank1 currency2) 7881)
	(= (bank-reserve bank2 currency0) 1747)
	(= (bank-reserve bank2 currency1) 2430)
	(= (bank-reserve bank2 currency2) 6128)
	(canwithdraw bank0)
	(canwithdraw bank1)
	(canwithdraw bank2)
	(currencyOf item0 currency1)
	(currencyOf item1 currency0)
	(currencyOf item2 currency1)
	(currencyOf item3 currency2)
	(currencyOf item4 currency0)
	(currencyOf item5 currency1)
	(canexchange changeOffice0)
	(canexchange changeOffice1)
	(canexchange changeOffice2)
	(different-currencies currency0 currency1)
	(different-currencies currency0 currency2)
	(different-currencies currency1 currency0)
	(different-currencies currency1 currency2)
	(different-currencies currency2 currency0)
	(different-currencies currency2 currency1)
	(link location0 location1 )
	(link location0 location2 )
	(link location0 location3 )
	(link location0 location4 )
	(link location0 location5 )
	(link location0 bank0 )
	(link location0 bank1 )
	(link location0 bank2 )
	(link location0 changeOffice0 )
	(link location0 changeOffice1 )
	(link location0 changeOffice2 )
	(link location1 location0 )
	(link location1 location2 )
	(link location1 location3 )
	(link location1 location4 )
	(link location1 location5 )
	(link location1 bank0 )
	(link location1 bank1 )
	(link location1 bank2 )
	(link location1 changeOffice0 )
	(link location1 changeOffice1 )
	(link location1 changeOffice2 )
	(link location2 location0 )
	(link location2 location1 )
	(link location2 location3 )
	(link location2 location4 )
	(link location2 location5 )
	(link location2 bank0 )
	(link location2 bank1 )
	(link location2 bank2 )
	(link location2 changeOffice0 )
	(link location2 changeOffice1 )
	(link location2 changeOffice2 )
	(link location3 location0 )
	(link location3 location1 )
	(link location3 location2 )
	(link location3 location4 )
	(link location3 location5 )
	(link location3 bank0 )
	(link location3 bank1 )
	(link location3 bank2 )
	(link location3 changeOffice0 )
	(link location3 changeOffice1 )
	(link location3 changeOffice2 )
	(link location4 location0 )
	(link location4 location1 )
	(link location4 location2 )
	(link location4 location3 )
	(link location4 location5 )
	(link location4 bank0 )
	(link location4 bank1 )
	(link location4 bank2 )
	(link location4 changeOffice0 )
	(link location4 changeOffice1 )
	(link location4 changeOffice2 )
	(link location5 location0 )
	(link location5 location1 )
	(link location5 location2 )
	(link location5 location3 )
	(link location5 location4 )
	(link location5 bank0 )
	(link location5 bank1 )
	(link location5 bank2 )
	(link location5 changeOffice0 )
	(link location5 changeOffice1 )
	(link location5 changeOffice2 )
	(link bank0 location0 )
	(link bank0 location1 )
	(link bank0 location2 )
	(link bank0 location3 )
	(link bank0 location4 )
	(link bank0 location5 )
	(link bank0 bank1 )
	(link bank0 bank2 )
	(link bank0 changeOffice0 )
	(link bank0 changeOffice1 )
	(link bank0 changeOffice2 )
	(link bank1 location0 )
	(link bank1 location1 )
	(link bank1 location2 )
	(link bank1 location3 )
	(link bank1 location4 )
	(link bank1 location5 )
	(link bank1 bank0 )
	(link bank1 bank2 )
	(link bank1 changeOffice0 )
	(link bank1 changeOffice1 )
	(link bank1 changeOffice2 )
	(link bank2 location0 )
	(link bank2 location1 )
	(link bank2 location2 )
	(link bank2 location3 )
	(link bank2 location4 )
	(link bank2 location5 )
	(link bank2 bank0 )
	(link bank2 bank1 )
	(link bank2 changeOffice0 )
	(link bank2 changeOffice1 )
	(link bank2 changeOffice2 )
	(link changeOffice0 location0 )
	(link changeOffice0 location1 )
	(link changeOffice0 location2 )
	(link changeOffice0 location3 )
	(link changeOffice0 location4 )
	(link changeOffice0 location5 )
	(link changeOffice0 bank0 )
	(link changeOffice0 bank1 )
	(link changeOffice0 bank2 )
	(link changeOffice0 changeOffice1 )
	(link changeOffice0 changeOffice2 )
	(link changeOffice1 location0 )
	(link changeOffice1 location1 )
	(link changeOffice1 location2 )
	(link changeOffice1 location3 )
	(link changeOffice1 location4 )
	(link changeOffice1 location5 )
	(link changeOffice1 bank0 )
	(link changeOffice1 bank1 )
	(link changeOffice1 bank2 )
	(link changeOffice1 changeOffice0 )
	(link changeOffice1 changeOffice2 )
	(link changeOffice2 location0 )
	(link changeOffice2 location1 )
	(link changeOffice2 location2 )
	(link changeOffice2 location3 )
	(link changeOffice2 location4 )
	(link changeOffice2 location5 )
	(link changeOffice2 bank0 )
	(link changeOffice2 bank1 )
	(link changeOffice2 bank2 )
	(link changeOffice2 changeOffice0 )
	(link changeOffice2 changeOffice1 ))

(:goal	(and

	(bought item0)
	(bought item5)
	(bought item3)
	(bought item1)
	(bought item4)
	(bought item2)
	(have_enough currency0)
	(have_enough currency1)
	(have_enough currency2)
		)
	)
)