(define (problem cashpoint0) (:domain cashpoint)
(:objects
	location0 location1 location2 location3 location4  - shop
	bank0 bank1  - bank
	changeOffice0 changeOffice1  - changeOffice
	item0 item1 item2 item3 item4  - item
	currency0 currency1 currency2 currency3  - currency
)

(:init
	(at location3)(available)
	(canbuy location0 item0)
	(canbuy location2 item1)
	(canbuy location2 item2)
	(canbuy location0 item3)
	(canbuy location2 item4)
	(= (currency_goal currency0) 217)
	(= (currency_goal currency1) 235)
	(= (currency_goal currency2) 242)
	(= (currency_goal currency3) 220)
	(= (price item0) 32)
	(= (price item1) 68)
	(= (price item2) 97)
	(= (price item3) 40)
	(= (price item4) 35)
	(= (balance currency0) 1433)
	(= (balance currency1) 1685)
	(= (balance currency2) 1762)
	(= (balance currency3) 1541)
	(= (exchangeRate currency0 currency1) 1.72776)
	(= (exchangeRate currency0 currency2) 1.73724)
	(= (exchangeRate currency0 currency3) 1.94543)
	(= (exchangeRate currency1 currency0) 0.578784)
	(= (exchangeRate currency1 currency2) 1.63836)
	(= (exchangeRate currency1 currency3) 0.774117)
	(= (exchangeRate currency2 currency0) 0.575627)
	(= (exchangeRate currency2 currency1) 0.610368)
	(= (exchangeRate currency2 currency3) 1.47154)
	(= (exchangeRate currency3 currency0) 0.514024)
	(= (exchangeRate currency3 currency1) 1.29179)
	(= (exchangeRate currency3 currency2) 0.67956)
	(= (inpocket currency0) 9)
	(= (inpocket currency1) 191)
	(= (inpocket currency2) 186)
	(= (inpocket currency3) 58)
	(= (points currency0) 25)
	(= (points currency1) 1)
	(= (points currency2) 1)
	(= (points currency3) 15)
	(= (bank-reserve bank0 currency0) 7971)
	(= (bank-reserve bank0 currency1) 3918)
	(= (bank-reserve bank0 currency2) 9200)
	(= (bank-reserve bank0 currency3) 4154)
	(= (bank-reserve bank1 currency0) 1378)
	(= (bank-reserve bank1 currency1) 4989)
	(= (bank-reserve bank1 currency2) 8696)
	(= (bank-reserve bank1 currency3) 7799)
	(canwithdraw bank0)
	(canwithdraw bank1)
	(currencyOf item0 currency1)
	(currencyOf item1 currency1)
	(currencyOf item2 currency2)
	(currencyOf item3 currency3)
	(currencyOf item4 currency0)
	(canexchange changeOffice0)
	(canexchange changeOffice1)
	(different-currencies currency0 currency1)
	(different-currencies currency0 currency2)
	(different-currencies currency0 currency3)
	(different-currencies currency1 currency0)
	(different-currencies currency1 currency2)
	(different-currencies currency1 currency3)
	(different-currencies currency2 currency0)
	(different-currencies currency2 currency1)
	(different-currencies currency2 currency3)
	(different-currencies currency3 currency0)
	(different-currencies currency3 currency1)
	(different-currencies currency3 currency2)
	(link location0 location1 )
	(link location0 location2 )
	(link location0 location3 )
	(link location0 location4 )
	(link location0 bank0 )
	(link location0 bank1 )
	(link location0 changeOffice0 )
	(link location0 changeOffice1 )
	(link location1 location0 )
	(link location1 location2 )
	(link location1 location3 )
	(link location1 location4 )
	(link location1 bank0 )
	(link location1 bank1 )
	(link location1 changeOffice0 )
	(link location1 changeOffice1 )
	(link location2 location0 )
	(link location2 location1 )
	(link location2 location3 )
	(link location2 location4 )
	(link location2 bank0 )
	(link location2 bank1 )
	(link location2 changeOffice0 )
	(link location2 changeOffice1 )
	(link location3 location0 )
	(link location3 location1 )
	(link location3 location2 )
	(link location3 location4 )
	(link location3 bank0 )
	(link location3 bank1 )
	(link location3 changeOffice0 )
	(link location3 changeOffice1 )
	(link location4 location0 )
	(link location4 location1 )
	(link location4 location2 )
	(link location4 location3 )
	(link location4 bank0 )
	(link location4 bank1 )
	(link location4 changeOffice0 )
	(link location4 changeOffice1 )
	(link bank0 location0 )
	(link bank0 location1 )
	(link bank0 location2 )
	(link bank0 location3 )
	(link bank0 location4 )
	(link bank0 bank1 )
	(link bank0 changeOffice0 )
	(link bank0 changeOffice1 )
	(link bank1 location0 )
	(link bank1 location1 )
	(link bank1 location2 )
	(link bank1 location3 )
	(link bank1 location4 )
	(link bank1 bank0 )
	(link bank1 changeOffice0 )
	(link bank1 changeOffice1 )
	(link changeOffice0 location0 )
	(link changeOffice0 location1 )
	(link changeOffice0 location2 )
	(link changeOffice0 location3 )
	(link changeOffice0 location4 )
	(link changeOffice0 bank0 )
	(link changeOffice0 bank1 )
	(link changeOffice0 changeOffice1 )
	(link changeOffice1 location0 )
	(link changeOffice1 location1 )
	(link changeOffice1 location2 )
	(link changeOffice1 location3 )
	(link changeOffice1 location4 )
	(link changeOffice1 bank0 )
	(link changeOffice1 bank1 )
	(link changeOffice1 changeOffice0 ))

(:goal	(and

	(bought item0)
	(bought item2)
	(bought item3)
	(bought item4)
	(bought item1)
	(have_enough currency3)
	(have_enough currency2)
	(have_enough currency0)
	(have_enough currency1)
		)
	)
)