(define (problem cashpoint0) (:domain cashpoint)
(:objects
	location0 location1 location2 location3  - shop
	bank0 bank1  - bank
	changeOffice0  - changeOffice
	item0 item1 item2 item3 item4  - item
	currency0 currency1  - currency
)

(:init
	(at location2)(available)
	(canbuy location3 item0)
	(canbuy location1 item1)
	(canbuy location3 item2)
	(canbuy location3 item3)
	(canbuy location3 item4)
	(= (currency_goal currency0) 222)
	(= (currency_goal currency1) 224)
	(= (price item0) 21)
	(= (price item1) 37)
	(= (price item2) 48)
	(= (price item3) 78)
	(= (price item4) 31)
	(= (balance currency0) 113)
	(= (balance currency1) 1181)
	(= (exchangeRate currency0 currency1) 1.91778)
	(= (exchangeRate currency1 currency0) 0.521435)
	(= (inpocket currency0) 162)
	(= (inpocket currency1) 105)
	(= (points currency0) 24)
	(= (points currency1) 23)
	(= (bank-reserve bank0 currency0) 6761)
	(= (bank-reserve bank0 currency1) 9488)
	(= (bank-reserve bank1 currency0) 4138)
	(= (bank-reserve bank1 currency1) 7000)
	(canwithdraw bank0)
	(canwithdraw bank1)
	(currencyOf item0 currency1)
	(currencyOf item1 currency1)
	(currencyOf item2 currency1)
	(currencyOf item3 currency1)
	(currencyOf item4 currency1)
	(canexchange changeOffice0)
	(different-currencies currency0 currency1)
	(different-currencies currency1 currency0)
	(link location0 location1 )
	(link location0 location2 )
	(link location0 location3 )
	(link location0 bank0 )
	(link location0 bank1 )
	(link location0 changeOffice0 )
	(link location1 location0 )
	(link location1 location2 )
	(link location1 location3 )
	(link location1 bank0 )
	(link location1 bank1 )
	(link location1 changeOffice0 )
	(link location2 location0 )
	(link location2 location1 )
	(link location2 location3 )
	(link location2 bank0 )
	(link location2 bank1 )
	(link location2 changeOffice0 )
	(link location3 location0 )
	(link location3 location1 )
	(link location3 location2 )
	(link location3 bank0 )
	(link location3 bank1 )
	(link location3 changeOffice0 )
	(link bank0 location0 )
	(link bank0 location1 )
	(link bank0 location2 )
	(link bank0 location3 )
	(link bank0 bank1 )
	(link bank0 changeOffice0 )
	(link bank1 location0 )
	(link bank1 location1 )
	(link bank1 location2 )
	(link bank1 location3 )
	(link bank1 bank0 )
	(link bank1 changeOffice0 )
	(link changeOffice0 location0 )
	(link changeOffice0 location1 )
	(link changeOffice0 location2 )
	(link changeOffice0 location3 )
	(link changeOffice0 bank0 )
	(link changeOffice0 bank1 ))

(:goal	(and

	(bought item4)
	(bought item2)
	(bought item0)
	(bought item1)
	(have_enough currency0)
	(have_enough currency1)
		)
	)
)