(define (problem cashpoint0) (:domain cashpoint)
(:objects
	location0 location1 location2 location3 location4  - shop
	bank0 bank1 bank2  - bank
	changeOffice0 changeOffice1 changeOffice2  - changeOffice
	item0 item1 item2 item3 item4  - item
	currency0 currency1 currency2 currency3 currency4  - currency
)

(:init
	(at location2)(available)
	(canbuy location1 item0)
	(canbuy location1 item1)
	(canbuy location0 item2)
	(canbuy location4 item3)
	(canbuy location0 item4)
	(= (currency_goal currency0) 205)
	(= (currency_goal currency1) 227)
	(= (currency_goal currency2) 247)
	(= (currency_goal currency3) 249)
	(= (currency_goal currency4) 235)
	(= (price item0) 18)
	(= (price item1) 3)
	(= (price item2) 56)
	(= (price item3) 36)
	(= (price item4) 45)
	(= (balance currency0) 447)
	(= (balance currency1) 1489)
	(= (balance currency2) 642)
	(= (balance currency3) 1527)
	(= (balance currency4) 1289)
	(= (exchangeRate currency0 currency1) 1.54753)
	(= (exchangeRate currency0 currency2) 1.97766)
	(= (exchangeRate currency0 currency3) 1.51462)
	(= (exchangeRate currency0 currency4) 1.63973)
	(= (exchangeRate currency1 currency0) 0.64619)
	(= (exchangeRate currency1 currency2) 0.652257)
	(= (exchangeRate currency1 currency3) 1.41317)
	(= (exchangeRate currency1 currency4) 0.598102)
	(= (exchangeRate currency2 currency0) 0.505648)
	(= (exchangeRate currency2 currency1) 1.53314)
	(= (exchangeRate currency2 currency3) 1.29997)
	(= (exchangeRate currency2 currency4) 1.69617)
	(= (exchangeRate currency3 currency0) 0.660232)
	(= (exchangeRate currency3 currency1) 0.707627)
	(= (exchangeRate currency3 currency2) 0.769251)
	(= (exchangeRate currency3 currency4) 1.93706)
	(= (exchangeRate currency4 currency0) 0.609857)
	(= (exchangeRate currency4 currency1) 1.67196)
	(= (exchangeRate currency4 currency2) 0.589563)
	(= (exchangeRate currency4 currency3) 0.516247)
	(= (inpocket currency0) 49)
	(= (inpocket currency1) 134)
	(= (inpocket currency2) 36)
	(= (inpocket currency3) 153)
	(= (inpocket currency4) 147)
	(= (points currency0) 39)
	(= (points currency1) 9)
	(= (points currency2) 10)
	(= (points currency3) 30)
	(= (points currency4) 18)
	(= (bank-reserve bank0 currency0) 6344)
	(= (bank-reserve bank0 currency1) 5769)
	(= (bank-reserve bank0 currency2) 3110)
	(= (bank-reserve bank0 currency3) 7908)
	(= (bank-reserve bank0 currency4) 7048)
	(= (bank-reserve bank1 currency0) 2035)
	(= (bank-reserve bank1 currency1) 5847)
	(= (bank-reserve bank1 currency2) 5115)
	(= (bank-reserve bank1 currency3) 9116)
	(= (bank-reserve bank1 currency4) 4936)
	(= (bank-reserve bank2 currency0) 9299)
	(= (bank-reserve bank2 currency1) 9876)
	(= (bank-reserve bank2 currency2) 4745)
	(= (bank-reserve bank2 currency3) 2557)
	(= (bank-reserve bank2 currency4) 194)
	(canwithdraw bank0)
	(canwithdraw bank1)
	(canwithdraw bank2)
	(currencyOf item0 currency2)
	(currencyOf item1 currency3)
	(currencyOf item2 currency1)
	(currencyOf item3 currency0)
	(currencyOf item4 currency2)
	(canexchange changeOffice0)
	(canexchange changeOffice1)
	(canexchange changeOffice2)
	(different-currencies currency0 currency1)
	(different-currencies currency0 currency2)
	(different-currencies currency0 currency3)
	(different-currencies currency0 currency4)
	(different-currencies currency1 currency0)
	(different-currencies currency1 currency2)
	(different-currencies currency1 currency3)
	(different-currencies currency1 currency4)
	(different-currencies currency2 currency0)
	(different-currencies currency2 currency1)
	(different-currencies currency2 currency3)
	(different-currencies currency2 currency4)
	(different-currencies currency3 currency0)
	(different-currencies currency3 currency1)
	(different-currencies currency3 currency2)
	(different-currencies currency3 currency4)
	(different-currencies currency4 currency0)
	(different-currencies currency4 currency1)
	(different-currencies currency4 currency2)
	(different-currencies currency4 currency3)
	(link location0 location1 )
	(link location0 location2 )
	(link location0 location3 )
	(link location0 location4 )
	(link location0 bank0 )
	(link location0 bank1 )
	(link location0 bank2 )
	(link location0 changeOffice0 )
	(link location0 changeOffice1 )
	(link location0 changeOffice2 )
	(link location1 location0 )
	(link location1 location2 )
	(link location1 location3 )
	(link location1 location4 )
	(link location1 bank0 )
	(link location1 bank1 )
	(link location1 bank2 )
	(link location1 changeOffice0 )
	(link location1 changeOffice1 )
	(link location1 changeOffice2 )
	(link location2 location0 )
	(link location2 location1 )
	(link location2 location3 )
	(link location2 location4 )
	(link location2 bank0 )
	(link location2 bank1 )
	(link location2 bank2 )
	(link location2 changeOffice0 )
	(link location2 changeOffice1 )
	(link location2 changeOffice2 )
	(link location3 location0 )
	(link location3 location1 )
	(link location3 location2 )
	(link location3 location4 )
	(link location3 bank0 )
	(link location3 bank1 )
	(link location3 bank2 )
	(link location3 changeOffice0 )
	(link location3 changeOffice1 )
	(link location3 changeOffice2 )
	(link location4 location0 )
	(link location4 location1 )
	(link location4 location2 )
	(link location4 location3 )
	(link location4 bank0 )
	(link location4 bank1 )
	(link location4 bank2 )
	(link location4 changeOffice0 )
	(link location4 changeOffice1 )
	(link location4 changeOffice2 )
	(link bank0 location0 )
	(link bank0 location1 )
	(link bank0 location2 )
	(link bank0 location3 )
	(link bank0 location4 )
	(link bank0 bank1 )
	(link bank0 bank2 )
	(link bank0 changeOffice0 )
	(link bank0 changeOffice1 )
	(link bank0 changeOffice2 )
	(link bank1 location0 )
	(link bank1 location1 )
	(link bank1 location2 )
	(link bank1 location3 )
	(link bank1 location4 )
	(link bank1 bank0 )
	(link bank1 bank2 )
	(link bank1 changeOffice0 )
	(link bank1 changeOffice1 )
	(link bank1 changeOffice2 )
	(link bank2 location0 )
	(link bank2 location1 )
	(link bank2 location2 )
	(link bank2 location3 )
	(link bank2 location4 )
	(link bank2 bank0 )
	(link bank2 bank1 )
	(link bank2 changeOffice0 )
	(link bank2 changeOffice1 )
	(link bank2 changeOffice2 )
	(link changeOffice0 location0 )
	(link changeOffice0 location1 )
	(link changeOffice0 location2 )
	(link changeOffice0 location3 )
	(link changeOffice0 location4 )
	(link changeOffice0 bank0 )
	(link changeOffice0 bank1 )
	(link changeOffice0 bank2 )
	(link changeOffice0 changeOffice1 )
	(link changeOffice0 changeOffice2 )
	(link changeOffice1 location0 )
	(link changeOffice1 location1 )
	(link changeOffice1 location2 )
	(link changeOffice1 location3 )
	(link changeOffice1 location4 )
	(link changeOffice1 bank0 )
	(link changeOffice1 bank1 )
	(link changeOffice1 bank2 )
	(link changeOffice1 changeOffice0 )
	(link changeOffice1 changeOffice2 )
	(link changeOffice2 location0 )
	(link changeOffice2 location1 )
	(link changeOffice2 location2 )
	(link changeOffice2 location3 )
	(link changeOffice2 location4 )
	(link changeOffice2 bank0 )
	(link changeOffice2 bank1 )
	(link changeOffice2 bank2 )
	(link changeOffice2 changeOffice0 )
	(link changeOffice2 changeOffice1 ))

(:goal	(and

	(bought item4)
	(bought item3)
	(bought item2)
	(bought item1)
	(bought item0)
	(have_enough currency1)
	(have_enough currency0)
	(have_enough currency3)
	(have_enough currency4)
	(have_enough currency2)
		)
	)
)