(define (problem cashpoint0) (:domain cashpoint)
(:objects
	location0 location1 location2 location3 location4  - shop
	bank0 bank1  - bank
	changeOffice0 changeOffice1  - changeOffice
	item0 item1 item2 item3 item4 item5  - item
	currency0 currency1 currency2 currency3  - currency
)

(:init
	(at location4)(available)
	(canbuy location0 item0)
	(canbuy location0 item1)
	(canbuy location1 item2)
	(canbuy location2 item3)
	(canbuy location2 item4)
	(canbuy location0 item5)
	(= (currency_goal currency0) 206)
	(= (currency_goal currency1) 213)
	(= (currency_goal currency2) 232)
	(= (currency_goal currency3) 214)
	(= (price item0) 95)
	(= (price item1) 28)
	(= (price item2) 80)
	(= (price item3) 66)
	(= (price item4) 31)
	(= (price item5) 67)
	(= (balance currency0) 565)
	(= (balance currency1) 32)
	(= (balance currency2) 1465)
	(= (balance currency3) 1260)
	(= (exchangeRate currency0 currency1) 1.85566)
	(= (exchangeRate currency0 currency2) 1.03011)
	(= (exchangeRate currency0 currency3) 0.790735)
	(= (exchangeRate currency1 currency0) 0.538891)
	(= (exchangeRate currency1 currency2) 1.41789)
	(= (exchangeRate currency1 currency3) 1.27625)
	(= (exchangeRate currency2 currency0) 0.970773)
	(= (exchangeRate currency2 currency1) 0.705273)
	(= (exchangeRate currency2 currency3) 1.83058)
	(= (exchangeRate currency3 currency0) 1.26465)
	(= (exchangeRate currency3 currency1) 0.783543)
	(= (exchangeRate currency3 currency2) 0.546276)
	(= (inpocket currency0) 64)
	(= (inpocket currency1) 95)
	(= (inpocket currency2) 167)
	(= (inpocket currency3) 21)
	(= (points currency0) 10)
	(= (points currency1) 20)
	(= (points currency2) 19)
	(= (points currency3) 10)
	(= (bank-reserve bank0 currency0) 3469)
	(= (bank-reserve bank0 currency1) 8730)
	(= (bank-reserve bank0 currency2) 7112)
	(= (bank-reserve bank0 currency3) 9583)
	(= (bank-reserve bank1 currency0) 3984)
	(= (bank-reserve bank1 currency1) 6345)
	(= (bank-reserve bank1 currency2) 4541)
	(= (bank-reserve bank1 currency3) 3211)
	(canwithdraw bank0)
	(canwithdraw bank1)
	(currencyOf item0 currency2)
	(currencyOf item1 currency2)
	(currencyOf item2 currency2)
	(currencyOf item3 currency0)
	(currencyOf item4 currency1)
	(currencyOf item5 currency0)
	(canexchange changeOffice0)
	(canexchange changeOffice1)
	(different-currencies currency0 currency1)
	(different-currencies currency0 currency2)
	(different-currencies currency0 currency3)
	(different-currencies currency1 currency0)
	(different-currencies currency1 currency2)
	(different-currencies currency1 currency3)
	(different-currencies currency2 currency0)
	(different-currencies currency2 currency1)
	(different-currencies currency2 currency3)
	(different-currencies currency3 currency0)
	(different-currencies currency3 currency1)
	(different-currencies currency3 currency2)
	(link location0 location1 )
	(link location0 location2 )
	(link location0 location3 )
	(link location0 location4 )
	(link location0 bank0 )
	(link location0 bank1 )
	(link location0 changeOffice0 )
	(link location0 changeOffice1 )
	(link location1 location0 )
	(link location1 location2 )
	(link location1 location3 )
	(link location1 location4 )
	(link location1 bank0 )
	(link location1 bank1 )
	(link location1 changeOffice0 )
	(link location1 changeOffice1 )
	(link location2 location0 )
	(link location2 location1 )
	(link location2 location3 )
	(link location2 location4 )
	(link location2 bank0 )
	(link location2 bank1 )
	(link location2 changeOffice0 )
	(link location2 changeOffice1 )
	(link location3 location0 )
	(link location3 location1 )
	(link location3 location2 )
	(link location3 location4 )
	(link location3 bank0 )
	(link location3 bank1 )
	(link location3 changeOffice0 )
	(link location3 changeOffice1 )
	(link location4 location0 )
	(link location4 location1 )
	(link location4 location2 )
	(link location4 location3 )
	(link location4 bank0 )
	(link location4 bank1 )
	(link location4 changeOffice0 )
	(link location4 changeOffice1 )
	(link bank0 location0 )
	(link bank0 location1 )
	(link bank0 location2 )
	(link bank0 location3 )
	(link bank0 location4 )
	(link bank0 bank1 )
	(link bank0 changeOffice0 )
	(link bank0 changeOffice1 )
	(link bank1 location0 )
	(link bank1 location1 )
	(link bank1 location2 )
	(link bank1 location3 )
	(link bank1 location4 )
	(link bank1 bank0 )
	(link bank1 changeOffice0 )
	(link bank1 changeOffice1 )
	(link changeOffice0 location0 )
	(link changeOffice0 location1 )
	(link changeOffice0 location2 )
	(link changeOffice0 location3 )
	(link changeOffice0 location4 )
	(link changeOffice0 bank0 )
	(link changeOffice0 bank1 )
	(link changeOffice0 changeOffice1 )
	(link changeOffice1 location0 )
	(link changeOffice1 location1 )
	(link changeOffice1 location2 )
	(link changeOffice1 location3 )
	(link changeOffice1 location4 )
	(link changeOffice1 bank0 )
	(link changeOffice1 bank1 )
	(link changeOffice1 changeOffice0 ))

(:goal	(and

	(bought item4)
	(bought item1)
	(bought item2)
	(bought item3)
	(bought item5)
	(bought item0)
	(have_enough currency0)
	(have_enough currency2)
	(have_enough currency3)
	(have_enough currency1)
		)
	)
)