(define (problem cashpoint0) (:domain cashpoint)
(:objects
	location0 location1 location2 location3  - shop
	bank0 bank1  - bank
	changeOffice0 changeOffice1  - changeOffice
	item0 item1 item2 item3 item4  - item
	currency0 currency1 currency2  - currency
)

(:init
	(at location2)(available)
	(canbuy location1 item0)
	(canbuy location1 item1)
	(canbuy location3 item2)
	(canbuy location3 item3)
	(canbuy location3 item4)
	(= (currency_goal currency0) 224)
	(= (currency_goal currency1) 225)
	(= (currency_goal currency2) 214)
	(= (price item0) 55)
	(= (price item1) 39)
	(= (price item2) 15)
	(= (price item3) 65)
	(= (price item4) 36)
	(= (balance currency0) 1361)
	(= (balance currency1) 1559)
	(= (balance currency2) 1121)
	(= (exchangeRate currency0 currency1) 1.71838)
	(= (exchangeRate currency0 currency2) 0.937223)
	(= (exchangeRate currency1 currency0) 0.581945)
	(= (exchangeRate currency1 currency2) 1.40356)
	(= (exchangeRate currency2 currency0) 1.06698)
	(= (exchangeRate currency2 currency1) 0.712473)
	(= (inpocket currency0) 115)
	(= (inpocket currency1) 193)
	(= (inpocket currency2) 48)
	(= (points currency0) 17)
	(= (points currency1) 10)
	(= (points currency2) 29)
	(= (bank-reserve bank0 currency0) 5412)
	(= (bank-reserve bank0 currency1) 4840)
	(= (bank-reserve bank0 currency2) 7780)
	(= (bank-reserve bank1 currency0) 6145)
	(= (bank-reserve bank1 currency1) 1926)
	(= (bank-reserve bank1 currency2) 9646)
	(canwithdraw bank0)
	(canwithdraw bank1)
	(currencyOf item0 currency0)
	(currencyOf item1 currency0)
	(currencyOf item2 currency2)
	(currencyOf item3 currency0)
	(currencyOf item4 currency2)
	(canexchange changeOffice0)
	(canexchange changeOffice1)
	(different-currencies currency0 currency1)
	(different-currencies currency0 currency2)
	(different-currencies currency1 currency0)
	(different-currencies currency1 currency2)
	(different-currencies currency2 currency0)
	(different-currencies currency2 currency1)
	(link location0 location1 )
	(link location0 location2 )
	(link location0 location3 )
	(link location0 bank0 )
	(link location0 bank1 )
	(link location0 changeOffice0 )
	(link location0 changeOffice1 )
	(link location1 location0 )
	(link location1 location2 )
	(link location1 location3 )
	(link location1 bank0 )
	(link location1 bank1 )
	(link location1 changeOffice0 )
	(link location1 changeOffice1 )
	(link location2 location0 )
	(link location2 location1 )
	(link location2 location3 )
	(link location2 bank0 )
	(link location2 bank1 )
	(link location2 changeOffice0 )
	(link location2 changeOffice1 )
	(link location3 location0 )
	(link location3 location1 )
	(link location3 location2 )
	(link location3 bank0 )
	(link location3 bank1 )
	(link location3 changeOffice0 )
	(link location3 changeOffice1 )
	(link bank0 location0 )
	(link bank0 location1 )
	(link bank0 location2 )
	(link bank0 location3 )
	(link bank0 bank1 )
	(link bank0 changeOffice0 )
	(link bank0 changeOffice1 )
	(link bank1 location0 )
	(link bank1 location1 )
	(link bank1 location2 )
	(link bank1 location3 )
	(link bank1 bank0 )
	(link bank1 changeOffice0 )
	(link bank1 changeOffice1 )
	(link changeOffice0 location0 )
	(link changeOffice0 location1 )
	(link changeOffice0 location2 )
	(link changeOffice0 location3 )
	(link changeOffice0 bank0 )
	(link changeOffice0 bank1 )
	(link changeOffice0 changeOffice1 )
	(link changeOffice1 location0 )
	(link changeOffice1 location1 )
	(link changeOffice1 location2 )
	(link changeOffice1 location3 )
	(link changeOffice1 bank0 )
	(link changeOffice1 bank1 )
	(link changeOffice1 changeOffice0 ))

(:goal	(and

	(bought item2)
	(bought item4)
	(bought item3)
	(bought item0)
	(have_enough currency2)
	(have_enough currency0)
	(have_enough currency1)
		)
	)
)