(define (problem cashpoint0) (:domain cashpoint)
(:objects
	location0 location1 location2  - shop
	bank0 bank1  - bank
	changeOffice0  - changeOffice
	item0 item1 item2  - item
	currency0 currency1  - currency
)

(:init
	(at location0)(available)
	(canbuy location2 item0)
	(canbuy location0 item1)
	(canbuy location0 item2)
	(= (currency_goal currency0) 238)
	(= (currency_goal currency1) 213)
	(= (price item0) 9)
	(= (price item1) 86)
	(= (price item2) 74)
	(= (balance currency0) 777)
	(= (balance currency1) 903)
	(= (exchangeRate currency0 currency1) 0.73278)
	(= (exchangeRate currency1 currency0) 1.36467)
	(= (inpocket currency0) 40)
	(= (inpocket currency1) 115)
	(= (points currency0) 16)
	(= (points currency1) 39)
	(= (bank-reserve bank0 currency0) 7492)
	(= (bank-reserve bank0 currency1) 5004)
	(= (bank-reserve bank1 currency0) 1105)
	(= (bank-reserve bank1 currency1) 622)
	(canwithdraw bank0)
	(canwithdraw bank1)
	(currencyOf item0 currency0)
	(currencyOf item1 currency1)
	(currencyOf item2 currency1)
	(canexchange changeOffice0)
	(different-currencies currency0 currency1)
	(different-currencies currency1 currency0)
	(link location0 location1 )
	(link location0 location2 )
	(link location0 bank0 )
	(link location0 bank1 )
	(link location0 changeOffice0 )
	(link location1 location0 )
	(link location1 location2 )
	(link location1 bank0 )
	(link location1 bank1 )
	(link location1 changeOffice0 )
	(link location2 location0 )
	(link location2 location1 )
	(link location2 bank0 )
	(link location2 bank1 )
	(link location2 changeOffice0 )
	(link bank0 location0 )
	(link bank0 location1 )
	(link bank0 location2 )
	(link bank0 bank1 )
	(link bank0 changeOffice0 )
	(link bank1 location0 )
	(link bank1 location1 )
	(link bank1 location2 )
	(link bank1 bank0 )
	(link bank1 changeOffice0 )
	(link changeOffice0 location0 )
	(link changeOffice0 location1 )
	(link changeOffice0 location2 )
	(link changeOffice0 bank0 )
	(link changeOffice0 bank1 ))

(:goal	(and

	(bought item2)
	(bought item1)
	(bought item0)
	(have_enough currency0)
	(have_enough currency1)
		)
	)
)