(define (problem cashpoint0) (:domain cashpoint)
(:objects
	location0 location1  - shop
	bank0 bank1  - bank
	changeOffice0  - changeOffice
	item0 item1  - item
	currency0 currency1 currency2  - currency
)

(:init
	(at location0)(available)
	(canbuy location1 item0)
	(canbuy location1 item1)
	(= (currency_goal currency0) 228)
	(= (currency_goal currency1) 230)
	(= (currency_goal currency2) 215)
	(= (price item0) 24)
	(= (price item1) 21)
	(= (balance currency0) 1777)
	(= (balance currency1) 1471)
	(= (balance currency2) 670)
	(= (exchangeRate currency0 currency1) 1.13329)
	(= (exchangeRate currency0 currency2) 0.637516)
	(= (exchangeRate currency1 currency0) 0.882387)
	(= (exchangeRate currency1 currency2) 0.542848)
	(= (exchangeRate currency2 currency0) 1.56859)
	(= (exchangeRate currency2 currency1) 1.84214)
	(= (inpocket currency0) 133)
	(= (inpocket currency1) 7)
	(= (inpocket currency2) 128)
	(= (points currency0) 17)
	(= (points currency1) 16)
	(= (points currency2) 11)
	(= (bank-reserve bank0 currency0) 3129)
	(= (bank-reserve bank0 currency1) 9590)
	(= (bank-reserve bank0 currency2) 2698)
	(= (bank-reserve bank1 currency0) 5275)
	(= (bank-reserve bank1 currency1) 8727)
	(= (bank-reserve bank1 currency2) 9152)
	(canwithdraw bank0)
	(canwithdraw bank1)
	(currencyOf item0 currency2)
	(currencyOf item1 currency0)
	(canexchange changeOffice0)
	(different-currencies currency0 currency1)
	(different-currencies currency0 currency2)
	(different-currencies currency1 currency0)
	(different-currencies currency1 currency2)
	(different-currencies currency2 currency0)
	(different-currencies currency2 currency1)
	(link location0 location1 )
	(link location0 bank0 )
	(link location0 bank1 )
	(link location0 changeOffice0 )
	(link location1 location0 )
	(link location1 bank0 )
	(link location1 bank1 )
	(link location1 changeOffice0 )
	(link bank0 location0 )
	(link bank0 location1 )
	(link bank0 bank1 )
	(link bank0 changeOffice0 )
	(link bank1 location0 )
	(link bank1 location1 )
	(link bank1 bank0 )
	(link bank1 changeOffice0 )
	(link changeOffice0 location0 )
	(link changeOffice0 location1 )
	(link changeOffice0 bank0 )
	(link changeOffice0 bank1 ))

(:goal	(and

	(bought item1)
	(bought item0)
	(have_enough currency2)
	(have_enough currency1)
	(have_enough currency0)
		)
	)
)