
(define (domain cashpoint)
(:requirements :typing :fluents :durative-actions
                 :duration-inequalities)
(:types shop bank changeOffice - location
        currency
        item)

(:predicates    (at ?a - location)
                (canwithdraw ?b - location)
                (canexchange ?b - changeOffice)
                (canbuy ?a - shop ?i - item)
                (bought ?i - item)
                (available)
                (have_enough ?z - currency)
                (link ?a ?b - location)
                (different-currencies ?c1 ?c2 - currency)
                (currencyOf ?i - item ?c - currency)
        )
(:functions     (inpocket ?z - currency)
                (balance ?z - currency)
                (exchangeRate ?z1 ?z2 - currency)
                (points ?z - currency)
                (currency_goal ?z1 - currency)
                (price ?i - item)
                (bank-reserve ?b - bank ?c - currency)
)

(:durative-action buy_with_cash
:parameters (?i - item ?a - shop ?z - currency)
:duration (= ?duration 1)
:condition (and     (at start (at ?a))
                    (at start (canbuy ?a ?i) )
                    (at start (available))
                    (at start (>= (inpocket ?z) (price ?i) ))
                    (at start (currencyOf ?i ?z))
                    (over all (at ?a))
                    (at end (>= (inpocket ?z) 0))
                     )
:effect (and    (at start (decrease (inpocket ?z) (price ?i) )) 
                (at start (not (available)))
                (at end (bought ?i) )
                (at end (available))
        ))
(:durative-action goto
:parameters (?a ?b - location)
:duration (= ?duration 5)
:condition (and (at start (at ?a)) (at start (available)) (at start (link ?a ?b)) )
:effect (and       (at start (not (at ?a))) (at start (not (available)))
                   (at end (at ?b))(at end (available))
        ))

(:action save_for_later
:parameters (?z - currency)
:precondition (and  (>= (inpocket ?z) (currency_goal ?z) ) )
:effect (and        (have_enough ?z)
                    (decrease (inpocket ?z) (currency_goal ?z) )
)
)
(:durative-action withdraw20
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 20))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 20))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 20))
   (at start (decrease (balance ?z1) 20))
   (at start (decrease (bank-reserve ?b ?z1) 20))
    (at end (available))))
(:durative-action withdraw25
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 25))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 25))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 25))
   (at start (decrease (balance ?z1) 25))
   (at start (decrease (bank-reserve ?b ?z1) 25))
    (at end (available))))
(:durative-action withdraw30
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 30))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 30))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 30))
   (at start (decrease (balance ?z1) 30))
   (at start (decrease (bank-reserve ?b ?z1) 30))
    (at end (available))))
(:durative-action withdraw35
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 35))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 35))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 35))
   (at start (decrease (balance ?z1) 35))
   (at start (decrease (bank-reserve ?b ?z1) 35))
    (at end (available))))
(:durative-action withdraw40
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 40))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 40))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 40))
   (at start (decrease (balance ?z1) 40))
   (at start (decrease (bank-reserve ?b ?z1) 40))
    (at end (available))))
(:durative-action withdraw45
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 45))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 45))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 45))
   (at start (decrease (balance ?z1) 45))
   (at start (decrease (bank-reserve ?b ?z1) 45))
    (at end (available))))
(:durative-action withdraw50
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 50))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 50))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 50))
   (at start (decrease (balance ?z1) 50))
   (at start (decrease (bank-reserve ?b ?z1) 50))
    (at end (available))))
(:durative-action withdraw55
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 55))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 55))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 55))
   (at start (decrease (balance ?z1) 55))
   (at start (decrease (bank-reserve ?b ?z1) 55))
    (at end (available))))
(:durative-action withdraw60
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 60))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 60))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 60))
   (at start (decrease (balance ?z1) 60))
   (at start (decrease (bank-reserve ?b ?z1) 60))
    (at end (available))))
(:durative-action withdraw65
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 65))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 65))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 65))
   (at start (decrease (balance ?z1) 65))
   (at start (decrease (bank-reserve ?b ?z1) 65))
    (at end (available))))
(:durative-action withdraw70
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 70))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 70))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 70))
   (at start (decrease (balance ?z1) 70))
   (at start (decrease (bank-reserve ?b ?z1) 70))
    (at end (available))))
(:durative-action withdraw75
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 75))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 75))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 75))
   (at start (decrease (balance ?z1) 75))
   (at start (decrease (bank-reserve ?b ?z1) 75))
    (at end (available))))
(:durative-action withdraw80
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 80))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 80))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 80))
   (at start (decrease (balance ?z1) 80))
   (at start (decrease (bank-reserve ?b ?z1) 80))
    (at end (available))))
(:durative-action withdraw85
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 85))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 85))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 85))
   (at start (decrease (balance ?z1) 85))
   (at start (decrease (bank-reserve ?b ?z1) 85))
    (at end (available))))
(:durative-action withdraw90
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 90))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 90))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 90))
   (at start (decrease (balance ?z1) 90))
   (at start (decrease (bank-reserve ?b ?z1) 90))
    (at end (available))))
(:durative-action withdraw95
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 95))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 95))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 95))
   (at start (decrease (balance ?z1) 95))
   (at start (decrease (bank-reserve ?b ?z1) 95))
    (at end (available))))
(:durative-action withdraw100
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 100))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 100))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 100))
   (at start (decrease (balance ?z1) 100))
   (at start (decrease (bank-reserve ?b ?z1) 100))
    (at end (available))))
(:durative-action withdraw105
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 105))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 105))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 105))
   (at start (decrease (balance ?z1) 105))
   (at start (decrease (bank-reserve ?b ?z1) 105))
    (at end (available))))
(:durative-action withdraw110
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 110))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 110))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 110))
   (at start (decrease (balance ?z1) 110))
   (at start (decrease (bank-reserve ?b ?z1) 110))
    (at end (available))))
(:durative-action withdraw115
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 115))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 115))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 115))
   (at start (decrease (balance ?z1) 115))
   (at start (decrease (bank-reserve ?b ?z1) 115))
    (at end (available))))
(:durative-action withdraw120
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 120))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 120))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 120))
   (at start (decrease (balance ?z1) 120))
   (at start (decrease (bank-reserve ?b ?z1) 120))
    (at end (available))))
(:durative-action withdraw125
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 125))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 125))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 125))
   (at start (decrease (balance ?z1) 125))
   (at start (decrease (bank-reserve ?b ?z1) 125))
    (at end (available))))
(:durative-action withdraw130
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 130))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 130))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 130))
   (at start (decrease (balance ?z1) 130))
   (at start (decrease (bank-reserve ?b ?z1) 130))
    (at end (available))))
(:durative-action withdraw135
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 135))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 135))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 135))
   (at start (decrease (balance ?z1) 135))
   (at start (decrease (bank-reserve ?b ?z1) 135))
    (at end (available))))
(:durative-action withdraw140
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 140))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 140))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 140))
   (at start (decrease (balance ?z1) 140))
   (at start (decrease (bank-reserve ?b ?z1) 140))
    (at end (available))))
(:durative-action withdraw145
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 145))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 145))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 145))
   (at start (decrease (balance ?z1) 145))
   (at start (decrease (bank-reserve ?b ?z1) 145))
    (at end (available))))
(:durative-action withdraw150
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 150))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 150))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 150))
   (at start (decrease (balance ?z1) 150))
   (at start (decrease (bank-reserve ?b ?z1) 150))
    (at end (available))))
(:durative-action withdraw155
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 155))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 155))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 155))
   (at start (decrease (balance ?z1) 155))
   (at start (decrease (bank-reserve ?b ?z1) 155))
    (at end (available))))
(:durative-action withdraw160
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 160))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 160))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 160))
   (at start (decrease (balance ?z1) 160))
   (at start (decrease (bank-reserve ?b ?z1) 160))
    (at end (available))))
(:durative-action withdraw165
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 165))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 165))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 165))
   (at start (decrease (balance ?z1) 165))
   (at start (decrease (bank-reserve ?b ?z1) 165))
    (at end (available))))
(:durative-action withdraw170
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 170))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 170))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 170))
   (at start (decrease (balance ?z1) 170))
   (at start (decrease (bank-reserve ?b ?z1) 170))
    (at end (available))))
(:durative-action withdraw175
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 175))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 175))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 175))
   (at start (decrease (balance ?z1) 175))
   (at start (decrease (bank-reserve ?b ?z1) 175))
    (at end (available))))
(:durative-action withdraw180
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 180))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 180))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 180))
   (at start (decrease (balance ?z1) 180))
   (at start (decrease (bank-reserve ?b ?z1) 180))
    (at end (available))))
(:durative-action withdraw185
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 185))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 185))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 185))
   (at start (decrease (balance ?z1) 185))
   (at start (decrease (bank-reserve ?b ?z1) 185))
    (at end (available))))
(:durative-action withdraw190
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 190))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 190))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 190))
   (at start (decrease (balance ?z1) 190))
   (at start (decrease (bank-reserve ?b ?z1) 190))
    (at end (available))))
(:durative-action withdraw195
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 195))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 195))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 195))
   (at start (decrease (balance ?z1) 195))
   (at start (decrease (bank-reserve ?b ?z1) 195))
    (at end (available))))
(:durative-action withdraw200
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 200))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 200))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 200))
   (at start (decrease (balance ?z1) 200))
   (at start (decrease (bank-reserve ?b ?z1) 200))
    (at end (available))))
(:durative-action withdraw205
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 205))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 205))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 205))
   (at start (decrease (balance ?z1) 205))
   (at start (decrease (bank-reserve ?b ?z1) 205))
    (at end (available))))
(:durative-action withdraw210
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 210))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 210))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 210))
   (at start (decrease (balance ?z1) 210))
   (at start (decrease (bank-reserve ?b ?z1) 210))
    (at end (available))))
(:durative-action withdraw215
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 215))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 215))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 215))
   (at start (decrease (balance ?z1) 215))
   (at start (decrease (bank-reserve ?b ?z1) 215))
    (at end (available))))
(:durative-action withdraw220
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 220))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 220))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 220))
   (at start (decrease (balance ?z1) 220))
   (at start (decrease (bank-reserve ?b ?z1) 220))
    (at end (available))))
(:durative-action withdraw225
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 225))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 225))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 225))
   (at start (decrease (balance ?z1) 225))
   (at start (decrease (bank-reserve ?b ?z1) 225))
    (at end (available))))
(:durative-action withdraw230
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 230))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 230))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 230))
   (at start (decrease (balance ?z1) 230))
   (at start (decrease (bank-reserve ?b ?z1) 230))
    (at end (available))))
(:durative-action withdraw235
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 235))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 235))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 235))
   (at start (decrease (balance ?z1) 235))
   (at start (decrease (bank-reserve ?b ?z1) 235))
    (at end (available))))
(:durative-action withdraw240
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 240))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 240))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 240))
   (at start (decrease (balance ?z1) 240))
   (at start (decrease (bank-reserve ?b ?z1) 240))
    (at end (available))))
(:durative-action withdraw245
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 245))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 245))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 245))
   (at start (decrease (balance ?z1) 245))
   (at start (decrease (bank-reserve ?b ?z1) 245))
    (at end (available))))
(:durative-action withdraw250
  :parameters (?b - bank ?z1 - currency)
  :duration (= ?duration 2)
:condition (and (over all (at ?b))
   (at start (>= (balance ?z1) 250))
    (at start (>= (balance ?z1) 0))
    (at end (>= (balance ?z1) 0))
   (at start (>= (bank-reserve ?b ?z1) 250))
    (at start (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (bank-reserve ?b ?z1) 0))
    (at end (>= (inpocket ?z1) 0))
    (at start (available))
    (at start (canwithdraw ?b)))
:effect (and (at start (not (available)))
   (at end (increase (inpocket ?z1) 250))
   (at start (decrease (balance ?z1) 250))
   (at start (decrease (bank-reserve ?b ?z1) 250))
    (at end (available))))
(:durative-action exchange_in_changeOffice20
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 20))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 20 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 20)) (at end (available))))
(:durative-action exchange_in_changeOffice25
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 25))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 25 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 25)) (at end (available))))
(:durative-action exchange_in_changeOffice30
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 30))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 30 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 30)) (at end (available))))
(:durative-action exchange_in_changeOffice35
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 35))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 35 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 35)) (at end (available))))
(:durative-action exchange_in_changeOffice40
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 40))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 40 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 40)) (at end (available))))
(:durative-action exchange_in_changeOffice45
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 45))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 45 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 45)) (at end (available))))
(:durative-action exchange_in_changeOffice50
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 50))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 50 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 50)) (at end (available))))
(:durative-action exchange_in_changeOffice55
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 55))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 55 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 55)) (at end (available))))
(:durative-action exchange_in_changeOffice60
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 60))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 60 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 60)) (at end (available))))
(:durative-action exchange_in_changeOffice65
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 65))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 65 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 65)) (at end (available))))
(:durative-action exchange_in_changeOffice70
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 70))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 70 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 70)) (at end (available))))
(:durative-action exchange_in_changeOffice75
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 75))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 75 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 75)) (at end (available))))
(:durative-action exchange_in_changeOffice80
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 80))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 80 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 80)) (at end (available))))
(:durative-action exchange_in_changeOffice85
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 85))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 85 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 85)) (at end (available))))
(:durative-action exchange_in_changeOffice90
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 90))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 90 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 90)) (at end (available))))
(:durative-action exchange_in_changeOffice95
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 95))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 95 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 95)) (at end (available))))
(:durative-action exchange_in_changeOffice100
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 100))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 100 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 100)) (at end (available))))
(:durative-action exchange_in_changeOffice105
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 105))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 105 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 105)) (at end (available))))
(:durative-action exchange_in_changeOffice110
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 110))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 110 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 110)) (at end (available))))
(:durative-action exchange_in_changeOffice115
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 115))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 115 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 115)) (at end (available))))
(:durative-action exchange_in_changeOffice120
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 120))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 120 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 120)) (at end (available))))
(:durative-action exchange_in_changeOffice125
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 125))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 125 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 125)) (at end (available))))
(:durative-action exchange_in_changeOffice130
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 130))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 130 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 130)) (at end (available))))
(:durative-action exchange_in_changeOffice135
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 135))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 135 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 135)) (at end (available))))
(:durative-action exchange_in_changeOffice140
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 140))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 140 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 140)) (at end (available))))
(:durative-action exchange_in_changeOffice145
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 145))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 145 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 145)) (at end (available))))
(:durative-action exchange_in_changeOffice150
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 150))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 150 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 150)) (at end (available))))
(:durative-action exchange_in_changeOffice155
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 155))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 155 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 155)) (at end (available))))
(:durative-action exchange_in_changeOffice160
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 160))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 160 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 160)) (at end (available))))
(:durative-action exchange_in_changeOffice165
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 165))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 165 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 165)) (at end (available))))
(:durative-action exchange_in_changeOffice170
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 170))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 170 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 170)) (at end (available))))
(:durative-action exchange_in_changeOffice175
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 175))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 175 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 175)) (at end (available))))
(:durative-action exchange_in_changeOffice180
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 180))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 180 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 180)) (at end (available))))
(:durative-action exchange_in_changeOffice185
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 185))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 185 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 185)) (at end (available))))
(:durative-action exchange_in_changeOffice190
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 190))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 190 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 190)) (at end (available))))
(:durative-action exchange_in_changeOffice195
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 195))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 195 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 195)) (at end (available))))
(:durative-action exchange_in_changeOffice200
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 200))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 200 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 200)) (at end (available))))
(:durative-action exchange_in_changeOffice205
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 205))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 205 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 205)) (at end (available))))
(:durative-action exchange_in_changeOffice210
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 210))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 210 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 210)) (at end (available))))
(:durative-action exchange_in_changeOffice215
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 215))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 215 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 215)) (at end (available))))
(:durative-action exchange_in_changeOffice220
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 220))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 220 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 220)) (at end (available))))
(:durative-action exchange_in_changeOffice225
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 225))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 225 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 225)) (at end (available))))
(:durative-action exchange_in_changeOffice230
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 230))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 230 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 230)) (at end (available))))
(:durative-action exchange_in_changeOffice235
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 235))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 235 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 235)) (at end (available))))
(:durative-action exchange_in_changeOffice240
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 240))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 240 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 240)) (at end (available))))
(:durative-action exchange_in_changeOffice245
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 245))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 245 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 245)) (at end (available))))
(:durative-action exchange_in_changeOffice250
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 250))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 250 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 250)) (at end (available))))
(:durative-action exchange_in_changeOffice255
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 255))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 255 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 255)) (at end (available))))
(:durative-action exchange_in_changeOffice260
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 260))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 260 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 260)) (at end (available))))
(:durative-action exchange_in_changeOffice265
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 265))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 265 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 265)) (at end (available))))
(:durative-action exchange_in_changeOffice270
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 270))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 270 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 270)) (at end (available))))
(:durative-action exchange_in_changeOffice275
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 275))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 275 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 275)) (at end (available))))
(:durative-action exchange_in_changeOffice280
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 280))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 280 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 280)) (at end (available))))
(:durative-action exchange_in_changeOffice285
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 285))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 285 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 285)) (at end (available))))
(:durative-action exchange_in_changeOffice290
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 290))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 290 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 290)) (at end (available))))
(:durative-action exchange_in_changeOffice295
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 295))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 295 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 295)) (at end (available))))
(:durative-action exchange_in_changeOffice300
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 300))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 300 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 300)) (at end (available))))
(:durative-action exchange_in_changeOffice305
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 305))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 305 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 305)) (at end (available))))
(:durative-action exchange_in_changeOffice310
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 310))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 310 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 310)) (at end (available))))
(:durative-action exchange_in_changeOffice315
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 315))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 315 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 315)) (at end (available))))
(:durative-action exchange_in_changeOffice320
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 320))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 320 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 320)) (at end (available))))
(:durative-action exchange_in_changeOffice325
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 325))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 325 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 325)) (at end (available))))
(:durative-action exchange_in_changeOffice330
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 330))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 330 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 330)) (at end (available))))
(:durative-action exchange_in_changeOffice335
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 335))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 335 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 335)) (at end (available))))
(:durative-action exchange_in_changeOffice340
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 340))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 340 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 340)) (at end (available))))
(:durative-action exchange_in_changeOffice345
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 345))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 345 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 345)) (at end (available))))
(:durative-action exchange_in_changeOffice350
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 350))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 350 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 350)) (at end (available))))
(:durative-action exchange_in_changeOffice355
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 355))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 355 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 355)) (at end (available))))
(:durative-action exchange_in_changeOffice360
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 360))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 360 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 360)) (at end (available))))
(:durative-action exchange_in_changeOffice365
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 365))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 365 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 365)) (at end (available))))
(:durative-action exchange_in_changeOffice370
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 370))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 370 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 370)) (at end (available))))
(:durative-action exchange_in_changeOffice375
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 375))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 375 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 375)) (at end (available))))
(:durative-action exchange_in_changeOffice380
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 380))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 380 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 380)) (at end (available))))
(:durative-action exchange_in_changeOffice385
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 385))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 385 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 385)) (at end (available))))
(:durative-action exchange_in_changeOffice390
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 390))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 390 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 390)) (at end (available))))
(:durative-action exchange_in_changeOffice395
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 395))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 395 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 395)) (at end (available))))
(:durative-action exchange_in_changeOffice400
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 400))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 400 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 400)) (at end (available))))
(:durative-action exchange_in_changeOffice405
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 405))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 405 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 405)) (at end (available))))
(:durative-action exchange_in_changeOffice410
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 410))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 410 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 410)) (at end (available))))
(:durative-action exchange_in_changeOffice415
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 415))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 415 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 415)) (at end (available))))
(:durative-action exchange_in_changeOffice420
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 420))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 420 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 420)) (at end (available))))
(:durative-action exchange_in_changeOffice425
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 425))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 425 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 425)) (at end (available))))
(:durative-action exchange_in_changeOffice430
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 430))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 430 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 430)) (at end (available))))
(:durative-action exchange_in_changeOffice435
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 435))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 435 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 435)) (at end (available))))
(:durative-action exchange_in_changeOffice440
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 440))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 440 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 440)) (at end (available))))
(:durative-action exchange_in_changeOffice445
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 445))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 445 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 445)) (at end (available))))
(:durative-action exchange_in_changeOffice450
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 450))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 450 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 450)) (at end (available))))
(:durative-action exchange_in_changeOffice455
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 455))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 455 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 455)) (at end (available))))
(:durative-action exchange_in_changeOffice460
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 460))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 460 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 460)) (at end (available))))
(:durative-action exchange_in_changeOffice465
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 465))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 465 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 465)) (at end (available))))
(:durative-action exchange_in_changeOffice470
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 470))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 470 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 470)) (at end (available))))
(:durative-action exchange_in_changeOffice475
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 475))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 475 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 475)) (at end (available))))
(:durative-action exchange_in_changeOffice480
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 480))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 480 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 480)) (at end (available))))
(:durative-action exchange_in_changeOffice485
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 485))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 485 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 485)) (at end (available))))
(:durative-action exchange_in_changeOffice490
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 490))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 490 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 490)) (at end (available))))
(:durative-action exchange_in_changeOffice495
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 495))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 495 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 495)) (at end (available))))
(:durative-action exchange_in_changeOffice500
:parameters (?b - changeOffice ?z1 ?z2 - currency)
:duration (= ?duration 2)
:condition (and (over all (at ?b)) (at start (canexchange ?b))
   (at start (different-currencies ?z1 ?z2))
  (at start (>= (inpocket ?z1) 500))
   (at start (>= (inpocket ?z2) 0)) (at end (>= (inpocket ?z2) 0))
   (at end (>= (inpocket ?z1) 0)) (at start (available)))
:effect (and (at start (not (available)))
  (at end (increase (inpocket ?z2) (* 500 (exchangeRate ?z1 ?z2))))
  (at start (decrease (inpocket ?z1) 500)) (at end (available))))
)