(define (domain terraria)
    (:requirements :typing :durative-actions :fluents :duration-inequalities)
    (:types resources products - items
            cobweb iron_bar lead_bar chain platinum_bar - resources
            silk bed wood chest platinum_sword - products
            location)
(:predicates (available)
            (placed_beds)
            (placed_chests)
            (placed_swords)
            (ready_loom)
            (ready_sawmill)
            (ready_workbench)
            (ready_anvil)
            (can_assemble ?loc - location)
            (can_lumber ?loc - location)
            (can_mine ?loc - location)
            (at ?loc - location)
            (link ?loc1 - location ?loc2 - location))
(:functions (stock ?e - items)
(distance ?loc1 - location ?loc2 - location))
(:durative-action cut_a_tree5
        :parameters(?a - wood ?loc1 - location)
        :duration (= ?duration 2)
        :condition (and (at start (available))
                        (at start (can_lumber ?loc1))
                        (at start (at ?loc1))
                        (at end (>= (stock ?a) 0))
                        (at start (>= (stock ?a) 0))
                        )
        :effect (and    (at start (not (available)))
                        (at start (increase (stock ?a) 5))
                        (at end (available))
        ))
        (:durative-action cut_a_tree20
        :parameters(?a - wood ?loc1 - location)
        :duration (= ?duration 2)
        :condition (and (at start (available))
                        (at start (can_lumber ?loc1))
                        (at start (at ?loc1))
                        (at end (>= (stock ?a) 0))
                        (at start (>= (stock ?a) 0))
                        )
        :effect (and    (at start (not (available)))
                        (at start (increase (stock ?a) 20))
                        (at end (available))
        ))
        (:durative-action cut_a_tree35
        :parameters(?a - wood ?loc1 - location)
        :duration (= ?duration 2)
        :condition (and (at start (available))
                        (at start (can_lumber ?loc1))
                        (at start (at ?loc1))
                        (at end (>= (stock ?a) 0))
                        (at start (>= (stock ?a) 0))
                        )
        :effect (and    (at start (not (available)))
                        (at start (increase (stock ?a) 35))
                        (at end (available))
        ))
        (:durative-action cut_a_tree50
        :parameters(?a - wood ?loc1 - location)
        :duration (= ?duration 2)
        :condition (and (at start (available))
                        (at start (can_lumber ?loc1))
                        (at start (at ?loc1))
                        (at end (>= (stock ?a) 0))
                        (at start (>= (stock ?a) 0))
                        )
        :effect (and    (at start (not (available)))
                        (at start (increase (stock ?a) 50))
                        (at end (available))
        ))
        (:durative-action cut_a_tree65
        :parameters(?a - wood ?loc1 - location)
        :duration (= ?duration 2)
        :condition (and (at start (available))
                        (at start (can_lumber ?loc1))
                        (at start (at ?loc1))
                        (at end (>= (stock ?a) 0))
                        (at start (>= (stock ?a) 0))
                        )
        :effect (and    (at start (not (available)))
                        (at start (increase (stock ?a) 65))
                        (at end (available))
        ))
        (:durative-action cut_a_tree80
        :parameters(?a - wood ?loc1 - location)
        :duration (= ?duration 2)
        :condition (and (at start (available))
                        (at start (can_lumber ?loc1))
                        (at start (at ?loc1))
                        (at end (>= (stock ?a) 0))
                        (at start (>= (stock ?a) 0))
                        )
        :effect (and    (at start (not (available)))
                        (at start (increase (stock ?a) 80))
                        (at end (available))
        ))
        (:durative-action cut_a_tree100
        :parameters(?a - wood ?loc1 - location)
        :duration (= ?duration 2)
        :condition (and (at start (available))
                        (at start (can_lumber ?loc1))
                        (at start (at ?loc1))
                        (at end (>= (stock ?a) 0))
                        (at start (>= (stock ?a) 0))
                        )
        :effect (and    (at start (not (available)))
                        (at start (increase (stock ?a) 100))
                        (at end (available))
        ))
        
(:durative-action find_resources10_5_1_5_5
    :parameters(?c - cobweb ?i - iron_bar ?lb - lead_bar ?pb - platinum_bar ?ch - chain ?loc1 - location)
    :duration (= ?duration 1)
    :condition (and (at start (available))
                    (at start (can_mine ?loc1))
                    (at start (at ?loc1))
                    (at end (>= (stock ?c) 0))
                    (at end (>= (stock ?i) 0))
                    (at end (>= (stock ?ch) 0))
                    (at end (>= (stock ?lb) 0))
    				(at end (>= (stock ?pb) 0))
                    )
    :effect (and    (at start (not (available)))
                    (at start (increase (stock ?c) 10))
                    (at start (increase (stock ?i) 5))
                    (at start (increase (stock ?lb) 5))
    				(at start (increase (stock ?pb) 5))
                    (at start (increase (stock ?ch) 1))
                    (at end (available))
    ))
                        (:durative-action find_resources10_5_1_5_16
    :parameters(?c - cobweb ?i - iron_bar ?lb - lead_bar ?pb - platinum_bar ?ch - chain ?loc1 - location)
    :duration (= ?duration 1)
    :condition (and (at start (available))
                    (at start (can_mine ?loc1))
                    (at start (at ?loc1))
                    (at end (>= (stock ?c) 0))
                    (at end (>= (stock ?i) 0))
                    (at end (>= (stock ?ch) 0))
                    (at end (>= (stock ?lb) 0))
    				(at end (>= (stock ?pb) 0))
                    )
    :effect (and    (at start (not (available)))
                    (at start (increase (stock ?c) 10))
                    (at start (increase (stock ?i) 5))
                    (at start (increase (stock ?lb) 5))
    				(at start (increase (stock ?pb) 16))
                    (at start (increase (stock ?ch) 1))
                    (at end (available))
    ))
                        (:durative-action find_resources10_5_1_16_5
    :parameters(?c - cobweb ?i - iron_bar ?lb - lead_bar ?pb - platinum_bar ?ch - chain ?loc1 - location)
    :duration (= ?duration 1)
    :condition (and (at start (available))
                    (at start (can_mine ?loc1))
                    (at start (at ?loc1))
                    (at end (>= (stock ?c) 0))
                    (at end (>= (stock ?i) 0))
                    (at end (>= (stock ?ch) 0))
                    (at end (>= (stock ?lb) 0))
    				(at end (>= (stock ?pb) 0))
                    )
    :effect (and    (at start (not (available)))
                    (at start (increase (stock ?c) 10))
                    (at start (increase (stock ?i) 5))
                    (at start (increase (stock ?lb) 16))
    				(at start (increase (stock ?pb) 5))
                    (at start (increase (stock ?ch) 1))
                    (at end (available))
    ))
                        (:durative-action find_resources10_5_2_5_5
    :parameters(?c - cobweb ?i - iron_bar ?lb - lead_bar ?pb - platinum_bar ?ch - chain ?loc1 - location)
    :duration (= ?duration 1)
    :condition (and (at start (available))
                    (at start (can_mine ?loc1))
                    (at start (at ?loc1))
                    (at end (>= (stock ?c) 0))
                    (at end (>= (stock ?i) 0))
                    (at end (>= (stock ?ch) 0))
                    (at end (>= (stock ?lb) 0))
    				(at end (>= (stock ?pb) 0))
                    )
    :effect (and    (at start (not (available)))
                    (at start (increase (stock ?c) 10))
                    (at start (increase (stock ?i) 5))
                    (at start (increase (stock ?lb) 5))
    				(at start (increase (stock ?pb) 5))
                    (at start (increase (stock ?ch) 2))
                    (at end (available))
    ))
                        (:durative-action find_resources10_5_2_5_16
    :parameters(?c - cobweb ?i - iron_bar ?lb - lead_bar ?pb - platinum_bar ?ch - chain ?loc1 - location)
    :duration (= ?duration 1)
    :condition (and (at start (available))
                    (at start (can_mine ?loc1))
                    (at start (at ?loc1))
                    (at end (>= (stock ?c) 0))
                    (at end (>= (stock ?i) 0))
                    (at end (>= (stock ?ch) 0))
                    (at end (>= (stock ?lb) 0))
    				(at end (>= (stock ?pb) 0))
                    )
    :effect (and    (at start (not (available)))
                    (at start (increase (stock ?c) 10))
                    (at start (increase (stock ?i) 5))
                    (at start (increase (stock ?lb) 5))
    				(at start (increase (stock ?pb) 16))
                    (at start (increase (stock ?ch) 2))
                    (at end (available))
    ))
                        (:durative-action find_resources10_5_2_16_5
    :parameters(?c - cobweb ?i - iron_bar ?lb - lead_bar ?pb - platinum_bar ?ch - chain ?loc1 - location)
    :duration (= ?duration 1)
    :condition (and (at start (available))
                    (at start (can_mine ?loc1))
                    (at start (at ?loc1))
                    (at end (>= (stock ?c) 0))
                    (at end (>= (stock ?i) 0))
                    (at end (>= (stock ?ch) 0))
                    (at end (>= (stock ?lb) 0))
    				(at end (>= (stock ?pb) 0))
                    )
    :effect (and    (at start (not (available)))
                    (at start (increase (stock ?c) 10))
                    (at start (increase (stock ?i) 5))
                    (at start (increase (stock ?lb) 16))
    				(at start (increase (stock ?pb) 5))
                    (at start (increase (stock ?ch) 2))
                    (at end (available))
    ))
                        (:durative-action find_resources10_5_3_5_5
    :parameters(?c - cobweb ?i - iron_bar ?lb - lead_bar ?pb - platinum_bar ?ch - chain ?loc1 - location)
    :duration (= ?duration 1)
    :condition (and (at start (available))
                    (at start (can_mine ?loc1))
                    (at start (at ?loc1))
                    (at end (>= (stock ?c) 0))
                    (at end (>= (stock ?i) 0))
                    (at end (>= (stock ?ch) 0))
                    (at end (>= (stock ?lb) 0))
    				(at end (>= (stock ?pb) 0))
                    )
    :effect (and    (at start (not (available)))
                    (at start (increase (stock ?c) 10))
                    (at start (increase (stock ?i) 5))
                    (at start (increase (stock ?lb) 5))
    				(at start (increase (stock ?pb) 5))
                    (at start (increase (stock ?ch) 3))
                    (at end (available))
    ))
                        (:durative-action find_resources10_5_3_5_16
    :parameters(?c - cobweb ?i - iron_bar ?lb - lead_bar ?pb - platinum_bar ?ch - chain ?loc1 - location)
    :duration (= ?duration 1)
    :condition (and (at start (available))
                    (at start (can_mine ?loc1))
                    (at start (at ?loc1))
                    (at end (>= (stock ?c) 0))
                    (at end (>= (stock ?i) 0))
                    (at end (>= (stock ?ch) 0))
                    (at end (>= (stock ?lb) 0))
    				(at end (>= (stock ?pb) 0))
                    )
    :effect (and    (at start (not (available)))
                    (at start (increase (stock ?c) 10))
                    (at start (increase (stock ?i) 5))
                    (at start (increase (stock ?lb) 5))
    				(at start (increase (stock ?pb) 16))
                    (at start (increase (stock ?ch) 3))
                    (at end (available))
    ))
                        (:durative-action find_resources10_5_3_16_5
    :parameters(?c - cobweb ?i - iron_bar ?lb - lead_bar ?pb - platinum_bar ?ch - chain ?loc1 - location)
    :duration (= ?duration 1)
    :condition (and (at start (available))
                    (at start (can_mine ?loc1))
                    (at start (at ?loc1))
                    (at end (>= (stock ?c) 0))
                    (at end (>= (stock ?i) 0))
                    (at end (>= (stock ?ch) 0))
                    (at end (>= (stock ?lb) 0))
    				(at end (>= (stock ?pb) 0))
                    )
    :effect (and    (at start (not (available)))
                    (at start (increase (stock ?c) 10))
                    (at start (increase (stock ?i) 5))
                    (at start (increase (stock ?lb) 16))
    				(at start (increase (stock ?pb) 5))
                    (at start (increase (stock ?ch) 3))
                    (at end (available))
    ))
                        (:durative-action find_resources10_5_4_5_5
    :parameters(?c - cobweb ?i - iron_bar ?lb - lead_bar ?pb - platinum_bar ?ch - chain ?loc1 - location)
    :duration (= ?duration 1)
    :condition (and (at start (available))
                    (at start (can_mine ?loc1))
                    (at start (at ?loc1))
                    (at end (>= (stock ?c) 0))
                    (at end (>= (stock ?i) 0))
                    (at end (>= (stock ?ch) 0))
                    (at end (>= (stock ?lb) 0))
    				(at end (>= (stock ?pb) 0))
                    )
    :effect (and    (at start (not (available)))
                    (at start (increase (stock ?c) 10))
                    (at start (increase (stock ?i) 5))
                    (at start (increase (stock ?lb) 5))
    				(at start (increase (stock ?pb) 5))
                    (at start (increase (stock ?ch) 4))
                    (at end (available))
    ))
                        (:durative-action find_resources10_5_4_5_16
    :parameters(?c - cobweb ?i - iron_bar ?lb - lead_bar ?pb - platinum_bar ?ch - chain ?loc1 - location)
    :duration (= ?duration 1)
    :condition (and (at start (available))
                    (at start (can_mine ?loc1))
                    (at start (at ?loc1))
                    (at end (>= (stock ?c) 0))
                    (at end (>= (stock ?i) 0))
                    (at end (>= (stock ?ch) 0))
                    (at end (>= (stock ?lb) 0))
    				(at end (>= (stock ?pb) 0))
                    )
    :effect (and    (at start (not (available)))
                    (at start (increase (stock ?c) 10))
                    (at start (increase (stock ?i) 5))
                    (at start (increase (stock ?lb) 5))
    				(at start (increase (stock ?pb) 16))
                    (at start (increase (stock ?ch) 4))
                    (at end (available))
    ))
                        (:durative-action find_resources10_5_4_16_5
    :parameters(?c - cobweb ?i - iron_bar ?lb - lead_bar ?pb - platinum_bar ?ch - chain ?loc1 - location)
    :duration (= ?duration 1)
    :condition (and (at start (available))
                    (at start (can_mine ?loc1))
                    (at start (at ?loc1))
                    (at end (>= (stock ?c) 0))
                    (at end (>= (stock ?i) 0))
                    (at end (>= (stock ?ch) 0))
                    (at end (>= (stock ?lb) 0))
    				(at end (>= (stock ?pb) 0))
                    )
    :effect (and    (at start (not (available)))
                    (at start (increase (stock ?c) 10))
                    (at start (increase (stock ?i) 5))
                    (at start (increase (stock ?lb) 16))
    				(at start (increase (stock ?pb) 5))
                    (at start (increase (stock ?ch) 4))
                    (at end (available))
    ))
                        (:durative-action find_resources10_5_5_5_5
    :parameters(?c - cobweb ?i - iron_bar ?lb - lead_bar ?pb - platinum_bar ?ch - chain ?loc1 - location)
    :duration (= ?duration 1)
    :condition (and (at start (available))
                    (at start (can_mine ?loc1))
                    (at start (at ?loc1))
                    (at end (>= (stock ?c) 0))
                    (at end (>= (stock ?i) 0))
                    (at end (>= (stock ?ch) 0))
                    (at end (>= (stock ?lb) 0))
    				(at end (>= (stock ?pb) 0))
                    )
    :effect (and    (at start (not (available)))
                    (at start (increase (stock ?c) 10))
                    (at start (increase (stock ?i) 5))
                    (at start (increase (stock ?lb) 5))
    				(at start (increase (stock ?pb) 5))
                    (at start (increase (stock ?ch) 5))
                    (at end (available))
    ))
                        (:durative-action find_resources10_5_6_5_5
    :parameters(?c - cobweb ?i - iron_bar ?lb - lead_bar ?pb - platinum_bar ?ch - chain ?loc1 - location)
    :duration (= ?duration 1)
    :condition (and (at start (available))
                    (at start (can_mine ?loc1))
                    (at start (at ?loc1))
                    (at end (>= (stock ?c) 0))
                    (at end (>= (stock ?i) 0))
                    (at end (>= (stock ?ch) 0))
                    (at end (>= (stock ?lb) 0))
    				(at end (>= (stock ?pb) 0))
                    )
    :effect (and    (at start (not (available)))
                    (at start (increase (stock ?c) 10))
                    (at start (increase (stock ?i) 5))
                    (at start (increase (stock ?lb) 5))
    				(at start (increase (stock ?pb) 5))
                    (at start (increase (stock ?ch) 6))
                    (at end (available))
    ))
                        (:durative-action find_resources10_5_7_5_5
    :parameters(?c - cobweb ?i - iron_bar ?lb - lead_bar ?pb - platinum_bar ?ch - chain ?loc1 - location)
    :duration (= ?duration 1)
    :condition (and (at start (available))
                    (at start (can_mine ?loc1))
                    (at start (at ?loc1))
                    (at end (>= (stock ?c) 0))
                    (at end (>= (stock ?i) 0))
                    (at end (>= (stock ?ch) 0))
                    (at end (>= (stock ?lb) 0))
    				(at end (>= (stock ?pb) 0))
                    )
    :effect (and    (at start (not (available)))
                    (at start (increase (stock ?c) 10))
                    (at start (increase (stock ?i) 5))
                    (at start (increase (stock ?lb) 5))
    				(at start (increase (stock ?pb) 5))
                    (at start (increase (stock ?ch) 7))
                    (at end (available))
    ))
                        (:durative-action find_resources10_5_8_5_5
    :parameters(?c - cobweb ?i - iron_bar ?lb - lead_bar ?pb - platinum_bar ?ch - chain ?loc1 - location)
    :duration (= ?duration 1)
    :condition (and (at start (available))
                    (at start (can_mine ?loc1))
                    (at start (at ?loc1))
                    (at end (>= (stock ?c) 0))
                    (at end (>= (stock ?i) 0))
                    (at end (>= (stock ?ch) 0))
                    (at end (>= (stock ?lb) 0))
    				(at end (>= (stock ?pb) 0))
                    )
    :effect (and    (at start (not (available)))
                    (at start (increase (stock ?c) 10))
                    (at start (increase (stock ?i) 5))
                    (at start (increase (stock ?lb) 5))
    				(at start (increase (stock ?pb) 5))
                    (at start (increase (stock ?ch) 8))
                    (at end (available))
    ))
                        (:durative-action find_resources10_5_9_5_5
    :parameters(?c - cobweb ?i - iron_bar ?lb - lead_bar ?pb - platinum_bar ?ch - chain ?loc1 - location)
    :duration (= ?duration 1)
    :condition (and (at start (available))
                    (at start (can_mine ?loc1))
                    (at start (at ?loc1))
                    (at end (>= (stock ?c) 0))
                    (at end (>= (stock ?i) 0))
                    (at end (>= (stock ?ch) 0))
                    (at end (>= (stock ?lb) 0))
    				(at end (>= (stock ?pb) 0))
                    )
    :effect (and    (at start (not (available)))
                    (at start (increase (stock ?c) 10))
                    (at start (increase (stock ?i) 5))
                    (at start (increase (stock ?lb) 5))
    				(at start (increase (stock ?pb) 5))
                    (at start (increase (stock ?ch) 9))
                    (at end (available))
    ))
                        (:durative-action find_resources10_5_10_5_5
    :parameters(?c - cobweb ?i - iron_bar ?lb - lead_bar ?pb - platinum_bar ?ch - chain ?loc1 - location)
    :duration (= ?duration 1)
    :condition (and (at start (available))
                    (at start (can_mine ?loc1))
                    (at start (at ?loc1))
                    (at end (>= (stock ?c) 0))
                    (at end (>= (stock ?i) 0))
                    (at end (>= (stock ?ch) 0))
                    (at end (>= (stock ?lb) 0))
    				(at end (>= (stock ?pb) 0))
                    )
    :effect (and    (at start (not (available)))
                    (at start (increase (stock ?c) 10))
                    (at start (increase (stock ?i) 5))
                    (at start (increase (stock ?lb) 5))
    				(at start (increase (stock ?pb) 5))
                    (at start (increase (stock ?ch) 10))
                    (at end (available))
    ))
                        (:durative-action find_resources10_16_1_5_5
    :parameters(?c - cobweb ?i - iron_bar ?lb - lead_bar ?pb - platinum_bar ?ch - chain ?loc1 - location)
    :duration (= ?duration 1)
    :condition (and (at start (available))
                    (at start (can_mine ?loc1))
                    (at start (at ?loc1))
                    (at end (>= (stock ?c) 0))
                    (at end (>= (stock ?i) 0))
                    (at end (>= (stock ?ch) 0))
                    (at end (>= (stock ?lb) 0))
    				(at end (>= (stock ?pb) 0))
                    )
    :effect (and    (at start (not (available)))
                    (at start (increase (stock ?c) 10))
                    (at start (increase (stock ?i) 16))
                    (at start (increase (stock ?lb) 5))
    				(at start (increase (stock ?pb) 5))
                    (at start (increase (stock ?ch) 1))
                    (at end (available))
    ))
                        (:durative-action find_resources10_16_2_5_5
    :parameters(?c - cobweb ?i - iron_bar ?lb - lead_bar ?pb - platinum_bar ?ch - chain ?loc1 - location)
    :duration (= ?duration 1)
    :condition (and (at start (available))
                    (at start (can_mine ?loc1))
                    (at start (at ?loc1))
                    (at end (>= (stock ?c) 0))
                    (at end (>= (stock ?i) 0))
                    (at end (>= (stock ?ch) 0))
                    (at end (>= (stock ?lb) 0))
    				(at end (>= (stock ?pb) 0))
                    )
    :effect (and    (at start (not (available)))
                    (at start (increase (stock ?c) 10))
                    (at start (increase (stock ?i) 16))
                    (at start (increase (stock ?lb) 5))
    				(at start (increase (stock ?pb) 5))
                    (at start (increase (stock ?ch) 2))
                    (at end (available))
    ))
                        (:durative-action find_resources10_16_3_5_5
    :parameters(?c - cobweb ?i - iron_bar ?lb - lead_bar ?pb - platinum_bar ?ch - chain ?loc1 - location)
    :duration (= ?duration 1)
    :condition (and (at start (available))
                    (at start (can_mine ?loc1))
                    (at start (at ?loc1))
                    (at end (>= (stock ?c) 0))
                    (at end (>= (stock ?i) 0))
                    (at end (>= (stock ?ch) 0))
                    (at end (>= (stock ?lb) 0))
    				(at end (>= (stock ?pb) 0))
                    )
    :effect (and    (at start (not (available)))
                    (at start (increase (stock ?c) 10))
                    (at start (increase (stock ?i) 16))
                    (at start (increase (stock ?lb) 5))
    				(at start (increase (stock ?pb) 5))
                    (at start (increase (stock ?ch) 3))
                    (at end (available))
    ))
                        (:durative-action find_resources10_16_4_5_5
    :parameters(?c - cobweb ?i - iron_bar ?lb - lead_bar ?pb - platinum_bar ?ch - chain ?loc1 - location)
    :duration (= ?duration 1)
    :condition (and (at start (available))
                    (at start (can_mine ?loc1))
                    (at start (at ?loc1))
                    (at end (>= (stock ?c) 0))
                    (at end (>= (stock ?i) 0))
                    (at end (>= (stock ?ch) 0))
                    (at end (>= (stock ?lb) 0))
    				(at end (>= (stock ?pb) 0))
                    )
    :effect (and    (at start (not (available)))
                    (at start (increase (stock ?c) 10))
                    (at start (increase (stock ?i) 16))
                    (at start (increase (stock ?lb) 5))
    				(at start (increase (stock ?pb) 5))
                    (at start (increase (stock ?ch) 4))
                    (at end (available))
    ))
                        (:durative-action find_resources20_5_1_5_5
    :parameters(?c - cobweb ?i - iron_bar ?lb - lead_bar ?pb - platinum_bar ?ch - chain ?loc1 - location)
    :duration (= ?duration 1)
    :condition (and (at start (available))
                    (at start (can_mine ?loc1))
                    (at start (at ?loc1))
                    (at end (>= (stock ?c) 0))
                    (at end (>= (stock ?i) 0))
                    (at end (>= (stock ?ch) 0))
                    (at end (>= (stock ?lb) 0))
    				(at end (>= (stock ?pb) 0))
                    )
    :effect (and    (at start (not (available)))
                    (at start (increase (stock ?c) 20))
                    (at start (increase (stock ?i) 5))
                    (at start (increase (stock ?lb) 5))
    				(at start (increase (stock ?pb) 5))
                    (at start (increase (stock ?ch) 1))
                    (at end (available))
    ))
                        (:durative-action find_resources20_5_2_5_5
    :parameters(?c - cobweb ?i - iron_bar ?lb - lead_bar ?pb - platinum_bar ?ch - chain ?loc1 - location)
    :duration (= ?duration 1)
    :condition (and (at start (available))
                    (at start (can_mine ?loc1))
                    (at start (at ?loc1))
                    (at end (>= (stock ?c) 0))
                    (at end (>= (stock ?i) 0))
                    (at end (>= (stock ?ch) 0))
                    (at end (>= (stock ?lb) 0))
    				(at end (>= (stock ?pb) 0))
                    )
    :effect (and    (at start (not (available)))
                    (at start (increase (stock ?c) 20))
                    (at start (increase (stock ?i) 5))
                    (at start (increase (stock ?lb) 5))
    				(at start (increase (stock ?pb) 5))
                    (at start (increase (stock ?ch) 2))
                    (at end (available))
    ))
                        (:durative-action find_resources20_5_3_5_5
    :parameters(?c - cobweb ?i - iron_bar ?lb - lead_bar ?pb - platinum_bar ?ch - chain ?loc1 - location)
    :duration (= ?duration 1)
    :condition (and (at start (available))
                    (at start (can_mine ?loc1))
                    (at start (at ?loc1))
                    (at end (>= (stock ?c) 0))
                    (at end (>= (stock ?i) 0))
                    (at end (>= (stock ?ch) 0))
                    (at end (>= (stock ?lb) 0))
    				(at end (>= (stock ?pb) 0))
                    )
    :effect (and    (at start (not (available)))
                    (at start (increase (stock ?c) 20))
                    (at start (increase (stock ?i) 5))
                    (at start (increase (stock ?lb) 5))
    				(at start (increase (stock ?pb) 5))
                    (at start (increase (stock ?ch) 3))
                    (at end (available))
    ))
                        (:durative-action find_resources20_5_4_5_5
    :parameters(?c - cobweb ?i - iron_bar ?lb - lead_bar ?pb - platinum_bar ?ch - chain ?loc1 - location)
    :duration (= ?duration 1)
    :condition (and (at start (available))
                    (at start (can_mine ?loc1))
                    (at start (at ?loc1))
                    (at end (>= (stock ?c) 0))
                    (at end (>= (stock ?i) 0))
                    (at end (>= (stock ?ch) 0))
                    (at end (>= (stock ?lb) 0))
    				(at end (>= (stock ?pb) 0))
                    )
    :effect (and    (at start (not (available)))
                    (at start (increase (stock ?c) 20))
                    (at start (increase (stock ?i) 5))
                    (at start (increase (stock ?lb) 5))
    				(at start (increase (stock ?pb) 5))
                    (at start (increase (stock ?ch) 4))
                    (at end (available))
    ))
                        (:durative-action find_resources20_5_5_5_5
    :parameters(?c - cobweb ?i - iron_bar ?lb - lead_bar ?pb - platinum_bar ?ch - chain ?loc1 - location)
    :duration (= ?duration 1)
    :condition (and (at start (available))
                    (at start (can_mine ?loc1))
                    (at start (at ?loc1))
                    (at end (>= (stock ?c) 0))
                    (at end (>= (stock ?i) 0))
                    (at end (>= (stock ?ch) 0))
                    (at end (>= (stock ?lb) 0))
    				(at end (>= (stock ?pb) 0))
                    )
    :effect (and    (at start (not (available)))
                    (at start (increase (stock ?c) 20))
                    (at start (increase (stock ?i) 5))
                    (at start (increase (stock ?lb) 5))
    				(at start (increase (stock ?pb) 5))
                    (at start (increase (stock ?ch) 5))
                    (at end (available))
    ))
                        
(:durative-action make_silk5
    :parameters(?s1 - silk ?cob - cobweb ?loc1 - location)
    :duration (= ?duration 5)
    :condition (and (at start (available))
                    (at start (ready_loom))
                    (at start (can_assemble ?loc1))
                    (at start (at ?loc1))
                    (at start (>= (stock ?cob) 35) )
                    (at end (>= (stock ?s1) 0) )
                    (at end (>= (stock ?cob) 0) )
                    )
    :effect (and    (at start (not (available)))
                    (at start (increase (stock ?s1) 5))
                    (at start (decrease (stock ?cob) 35 ))
                    (at end (available))
    ))
    (:durative-action make_silk20
    :parameters(?s1 - silk ?cob - cobweb ?loc1 - location)
    :duration (= ?duration 5)
    :condition (and (at start (available))
                    (at start (ready_loom))
                    (at start (can_assemble ?loc1))
                    (at start (at ?loc1))
                    (at start (>= (stock ?cob) 140) )
                    (at end (>= (stock ?s1) 0) )
                    (at end (>= (stock ?cob) 0) )
                    )
    :effect (and    (at start (not (available)))
                    (at start (increase (stock ?s1) 20))
                    (at start (decrease (stock ?cob) 140 ))
                    (at end (available))
    ))
    (:durative-action make_silk35
    :parameters(?s1 - silk ?cob - cobweb ?loc1 - location)
    :duration (= ?duration 5)
    :condition (and (at start (available))
                    (at start (ready_loom))
                    (at start (can_assemble ?loc1))
                    (at start (at ?loc1))
                    (at start (>= (stock ?cob) 245) )
                    (at end (>= (stock ?s1) 0) )
                    (at end (>= (stock ?cob) 0) )
                    )
    :effect (and    (at start (not (available)))
                    (at start (increase (stock ?s1) 35))
                    (at start (decrease (stock ?cob) 245 ))
                    (at end (available))
    ))
    (:durative-action make_silk50
    :parameters(?s1 - silk ?cob - cobweb ?loc1 - location)
    :duration (= ?duration 5)
    :condition (and (at start (available))
                    (at start (ready_loom))
                    (at start (can_assemble ?loc1))
                    (at start (at ?loc1))
                    (at start (>= (stock ?cob) 350) )
                    (at end (>= (stock ?s1) 0) )
                    (at end (>= (stock ?cob) 0) )
                    )
    :effect (and    (at start (not (available)))
                    (at start (increase (stock ?s1) 50))
                    (at start (decrease (stock ?cob) 350 ))
                    (at end (available))
    ))
    (:durative-action make_silk65
    :parameters(?s1 - silk ?cob - cobweb ?loc1 - location)
    :duration (= ?duration 5)
    :condition (and (at start (available))
                    (at start (ready_loom))
                    (at start (can_assemble ?loc1))
                    (at start (at ?loc1))
                    (at start (>= (stock ?cob) 455) )
                    (at end (>= (stock ?s1) 0) )
                    (at end (>= (stock ?cob) 0) )
                    )
    :effect (and    (at start (not (available)))
                    (at start (increase (stock ?s1) 65))
                    (at start (decrease (stock ?cob) 455 ))
                    (at end (available))
    ))
    (:durative-action make_silk80
    :parameters(?s1 - silk ?cob - cobweb ?loc1 - location)
    :duration (= ?duration 5)
    :condition (and (at start (available))
                    (at start (ready_loom))
                    (at start (can_assemble ?loc1))
                    (at start (at ?loc1))
                    (at start (>= (stock ?cob) 560) )
                    (at end (>= (stock ?s1) 0) )
                    (at end (>= (stock ?cob) 0) )
                    )
    :effect (and    (at start (not (available)))
                    (at start (increase (stock ?s1) 80))
                    (at start (decrease (stock ?cob) 560 ))
                    (at end (available))
    ))
    (:durative-action make_silk100
    :parameters(?s1 - silk ?cob - cobweb ?loc1 - location)
    :duration (= ?duration 5)
    :condition (and (at start (available))
                    (at start (ready_loom))
                    (at start (can_assemble ?loc1))
                    (at start (at ?loc1))
                    (at start (>= (stock ?cob) 700) )
                    (at end (>= (stock ?s1) 0) )
                    (at end (>= (stock ?cob) 0) )
                    )
    :effect (and    (at start (not (available)))
                    (at start (increase (stock ?s1) 100))
                    (at start (decrease (stock ?cob) 700 ))
                    (at end (available))
    ))
    
(:durative-action assemble_a_loom
    :parameters(?w1 - wood ?loc1 - location)
    :duration (= ?duration 5)
    :condition (and (at start (available))
                    (at start (ready_sawmill))
                    (at start (>= (stock ?w1) 12) )
                    (at start (at ?loc1))
                    (at start (can_assemble ?loc1)) 
                    (at end (>= (stock ?w1) 0) )
                    )
    :effect (and    (at start (not (available)))
                    (at end (decrease (stock ?w1) 12))
                    (at end (available))
                    (at end (ready_loom))
    ))
    
(:durative-action assemble_a_sawmill
    :parameters(?w1 - wood ?iron - iron_bar ?ch - chain ?loc1 - location)
    :duration (= ?duration 5)
    :condition (and (at start (available))
                    (at start (ready_workbench))
                    (at start (>= (stock ?w1) 10) ) 
                    (at start (>= (stock ?iron) 2) )
                    (at start (>= (stock ?ch) 1) )
                    (at start (at ?loc1))
                    (at start (can_assemble ?loc1))
                    (at end (>= (stock ?w1) 0) )
                    (at end (>= (stock ?iron) 0) )
                    (at end (>= (stock ?ch) 0) )
                    )
    :effect (and    (at start (not (available)))
                    (at end (decrease (stock ?w1) 10))
                    (at end (decrease (stock ?iron) 2) )
                    (at end (decrease (stock ?ch) 1) )
                    (at end (available))
                    (at end (ready_sawmill))
    ))
    
(:durative-action assemble_an_anvil
:parameters(?iron - iron_bar ?loc1 - location)
:duration (= ?duration 7)
:condition (and (at start (available))
                (at start (ready_workbench))
                (at start (>= (stock ?iron) 5) )
				(at end (>= (stock ?iron) 0) )
                (at start (at ?loc1))
                (at start (can_assemble ?loc1))
                )
:effect (and    (at start (not (available)))
                (at start (decrease (stock ?iron) 5) )
                (at end (available))
                (at end (ready_anvil))
))
    
(:durative-action assemble_beds3
        :parameters(?w1 - wood ?s1 - silk ?b - bed ?loc1 - location)
        :duration (= ?duration 5)
        :condition (and (at start (available))
                        (at start (ready_sawmill)) 
                        (at start (at ?loc1))
                        (at start (can_assemble ?loc1))
                        (at start (>= (stock ?w1) 45 ) ) 
                        (at start (>= (stock ?s1) 15 ) )
                        (at end (>= (stock ?w1) 0 ) ) 
                        (at end (>= (stock ?s1) 0 ) )
                        (at start (>= (stock ?w1) 0 ) ) 
                        (at start (>= (stock ?s1) 0 ) )
        				(at start (>= (stock ?b) 0 ) )
                        )
        :effect (and    (at start (not (available)))
                        (at start (increase (stock ?b) 3) )
                        (at start (decrease (stock ?w1) 45 ) )
                        (at start (decrease (stock ?s1) 15 ) )
                        (at end (available))
        ))
        (:durative-action assemble_beds6
        :parameters(?w1 - wood ?s1 - silk ?b - bed ?loc1 - location)
        :duration (= ?duration 5)
        :condition (and (at start (available))
                        (at start (ready_sawmill)) 
                        (at start (at ?loc1))
                        (at start (can_assemble ?loc1))
                        (at start (>= (stock ?w1) 90 ) ) 
                        (at start (>= (stock ?s1) 30 ) )
                        (at end (>= (stock ?w1) 0 ) ) 
                        (at end (>= (stock ?s1) 0 ) )
                        (at start (>= (stock ?w1) 0 ) ) 
                        (at start (>= (stock ?s1) 0 ) )
        				(at start (>= (stock ?b) 0 ) )
                        )
        :effect (and    (at start (not (available)))
                        (at start (increase (stock ?b) 6) )
                        (at start (decrease (stock ?w1) 90 ) )
                        (at start (decrease (stock ?s1) 30 ) )
                        (at end (available))
        ))
        (:durative-action assemble_beds9
        :parameters(?w1 - wood ?s1 - silk ?b - bed ?loc1 - location)
        :duration (= ?duration 5)
        :condition (and (at start (available))
                        (at start (ready_sawmill)) 
                        (at start (at ?loc1))
                        (at start (can_assemble ?loc1))
                        (at start (>= (stock ?w1) 135 ) ) 
                        (at start (>= (stock ?s1) 45 ) )
                        (at end (>= (stock ?w1) 0 ) ) 
                        (at end (>= (stock ?s1) 0 ) )
                        (at start (>= (stock ?w1) 0 ) ) 
                        (at start (>= (stock ?s1) 0 ) )
        				(at start (>= (stock ?b) 0 ) )
                        )
        :effect (and    (at start (not (available)))
                        (at start (increase (stock ?b) 9) )
                        (at start (decrease (stock ?w1) 135 ) )
                        (at start (decrease (stock ?s1) 45 ) )
                        (at end (available))
        ))
        (:durative-action assemble_beds12
        :parameters(?w1 - wood ?s1 - silk ?b - bed ?loc1 - location)
        :duration (= ?duration 5)
        :condition (and (at start (available))
                        (at start (ready_sawmill)) 
                        (at start (at ?loc1))
                        (at start (can_assemble ?loc1))
                        (at start (>= (stock ?w1) 180 ) ) 
                        (at start (>= (stock ?s1) 60 ) )
                        (at end (>= (stock ?w1) 0 ) ) 
                        (at end (>= (stock ?s1) 0 ) )
                        (at start (>= (stock ?w1) 0 ) ) 
                        (at start (>= (stock ?s1) 0 ) )
        				(at start (>= (stock ?b) 0 ) )
                        )
        :effect (and    (at start (not (available)))
                        (at start (increase (stock ?b) 12) )
                        (at start (decrease (stock ?w1) 180 ) )
                        (at start (decrease (stock ?s1) 60 ) )
                        (at end (available))
        ))
        (:durative-action assemble_beds15
        :parameters(?w1 - wood ?s1 - silk ?b - bed ?loc1 - location)
        :duration (= ?duration 5)
        :condition (and (at start (available))
                        (at start (ready_sawmill)) 
                        (at start (at ?loc1))
                        (at start (can_assemble ?loc1))
                        (at start (>= (stock ?w1) 225 ) ) 
                        (at start (>= (stock ?s1) 75 ) )
                        (at end (>= (stock ?w1) 0 ) ) 
                        (at end (>= (stock ?s1) 0 ) )
                        (at start (>= (stock ?w1) 0 ) ) 
                        (at start (>= (stock ?s1) 0 ) )
        				(at start (>= (stock ?b) 0 ) )
                        )
        :effect (and    (at start (not (available)))
                        (at start (increase (stock ?b) 15) )
                        (at start (decrease (stock ?w1) 225 ) )
                        (at start (decrease (stock ?s1) 75 ) )
                        (at end (available))
        ))
        (:durative-action assemble_beds18
        :parameters(?w1 - wood ?s1 - silk ?b - bed ?loc1 - location)
        :duration (= ?duration 5)
        :condition (and (at start (available))
                        (at start (ready_sawmill)) 
                        (at start (at ?loc1))
                        (at start (can_assemble ?loc1))
                        (at start (>= (stock ?w1) 270 ) ) 
                        (at start (>= (stock ?s1) 90 ) )
                        (at end (>= (stock ?w1) 0 ) ) 
                        (at end (>= (stock ?s1) 0 ) )
                        (at start (>= (stock ?w1) 0 ) ) 
                        (at start (>= (stock ?s1) 0 ) )
        				(at start (>= (stock ?b) 0 ) )
                        )
        :effect (and    (at start (not (available)))
                        (at start (increase (stock ?b) 18) )
                        (at start (decrease (stock ?w1) 270 ) )
                        (at start (decrease (stock ?s1) 90 ) )
                        (at end (available))
        ))
        (:durative-action assemble_beds21
        :parameters(?w1 - wood ?s1 - silk ?b - bed ?loc1 - location)
        :duration (= ?duration 5)
        :condition (and (at start (available))
                        (at start (ready_sawmill)) 
                        (at start (at ?loc1))
                        (at start (can_assemble ?loc1))
                        (at start (>= (stock ?w1) 315 ) ) 
                        (at start (>= (stock ?s1) 105 ) )
                        (at end (>= (stock ?w1) 0 ) ) 
                        (at end (>= (stock ?s1) 0 ) )
                        (at start (>= (stock ?w1) 0 ) ) 
                        (at start (>= (stock ?s1) 0 ) )
        				(at start (>= (stock ?b) 0 ) )
                        )
        :effect (and    (at start (not (available)))
                        (at start (increase (stock ?b) 21) )
                        (at start (decrease (stock ?w1) 315 ) )
                        (at start (decrease (stock ?s1) 105 ) )
                        (at end (available))
        ))
        (:durative-action assemble_beds24
        :parameters(?w1 - wood ?s1 - silk ?b - bed ?loc1 - location)
        :duration (= ?duration 5)
        :condition (and (at start (available))
                        (at start (ready_sawmill)) 
                        (at start (at ?loc1))
                        (at start (can_assemble ?loc1))
                        (at start (>= (stock ?w1) 360 ) ) 
                        (at start (>= (stock ?s1) 120 ) )
                        (at end (>= (stock ?w1) 0 ) ) 
                        (at end (>= (stock ?s1) 0 ) )
                        (at start (>= (stock ?w1) 0 ) ) 
                        (at start (>= (stock ?s1) 0 ) )
        				(at start (>= (stock ?b) 0 ) )
                        )
        :effect (and    (at start (not (available)))
                        (at start (increase (stock ?b) 24) )
                        (at start (decrease (stock ?w1) 360 ) )
                        (at start (decrease (stock ?s1) 120 ) )
                        (at end (available))
        ))
        (:durative-action assemble_beds27
        :parameters(?w1 - wood ?s1 - silk ?b - bed ?loc1 - location)
        :duration (= ?duration 5)
        :condition (and (at start (available))
                        (at start (ready_sawmill)) 
                        (at start (at ?loc1))
                        (at start (can_assemble ?loc1))
                        (at start (>= (stock ?w1) 405 ) ) 
                        (at start (>= (stock ?s1) 135 ) )
                        (at end (>= (stock ?w1) 0 ) ) 
                        (at end (>= (stock ?s1) 0 ) )
                        (at start (>= (stock ?w1) 0 ) ) 
                        (at start (>= (stock ?s1) 0 ) )
        				(at start (>= (stock ?b) 0 ) )
                        )
        :effect (and    (at start (not (available)))
                        (at start (increase (stock ?b) 27) )
                        (at start (decrease (stock ?w1) 405 ) )
                        (at start (decrease (stock ?s1) 135 ) )
                        (at end (available))
        ))
        (:durative-action assemble_beds30
        :parameters(?w1 - wood ?s1 - silk ?b - bed ?loc1 - location)
        :duration (= ?duration 5)
        :condition (and (at start (available))
                        (at start (ready_sawmill)) 
                        (at start (at ?loc1))
                        (at start (can_assemble ?loc1))
                        (at start (>= (stock ?w1) 450 ) ) 
                        (at start (>= (stock ?s1) 150 ) )
                        (at end (>= (stock ?w1) 0 ) ) 
                        (at end (>= (stock ?s1) 0 ) )
                        (at start (>= (stock ?w1) 0 ) ) 
                        (at start (>= (stock ?s1) 0 ) )
        				(at start (>= (stock ?b) 0 ) )
                        )
        :effect (and    (at start (not (available)))
                        (at start (increase (stock ?b) 30) )
                        (at start (decrease (stock ?w1) 450 ) )
                        (at start (decrease (stock ?s1) 150 ) )
                        (at end (available))
        ))
        
(:durative-action produce_chests3
        :parameters(?c - chest ?w1 - wood ?lb - lead_bar ?i - iron_bar ?loc1 - location)
        :duration (= ?duration 5)
        :condition (and (at start (available))
                        (at start (ready_workbench)) 
                        (at start (>= (stock ?c) 0))
                        (at start (at ?loc1))
                        (at start (can_assemble ?loc1))
                        (at start (>= (stock ?w1) 24 ) ) 
                        (at start (>= (stock ?lb) 6 ) )
                        (at start (>= (stock ?i) 6 ) )
                        (at end (>= (stock ?w1) 0 ) ) 
                        (at end (>= (stock ?lb) 0 ) )
                        (at end (>= (stock ?i) 0 ) )
                        )
        :effect (and    (at start (not (available)))
                        (at start (increase (stock ?c) 3) )
                        (at start (decrease (stock ?w1) 24 ) )
                        (at start (decrease (stock ?lb) 6 ) )
                        (at start (decrease (stock ?i) 6 ) )
                        (at end (available))
        ))
                (:durative-action produce_chests6
        :parameters(?c - chest ?w1 - wood ?lb - lead_bar ?i - iron_bar ?loc1 - location)
        :duration (= ?duration 5)
        :condition (and (at start (available))
                        (at start (ready_workbench)) 
                        (at start (>= (stock ?c) 0))
                        (at start (at ?loc1))
                        (at start (can_assemble ?loc1))
                        (at start (>= (stock ?w1) 48 ) ) 
                        (at start (>= (stock ?lb) 12 ) )
                        (at start (>= (stock ?i) 12 ) )
                        (at end (>= (stock ?w1) 0 ) ) 
                        (at end (>= (stock ?lb) 0 ) )
                        (at end (>= (stock ?i) 0 ) )
                        )
        :effect (and    (at start (not (available)))
                        (at start (increase (stock ?c) 6) )
                        (at start (decrease (stock ?w1) 48 ) )
                        (at start (decrease (stock ?lb) 12 ) )
                        (at start (decrease (stock ?i) 12 ) )
                        (at end (available))
        ))
                (:durative-action produce_chests9
        :parameters(?c - chest ?w1 - wood ?lb - lead_bar ?i - iron_bar ?loc1 - location)
        :duration (= ?duration 5)
        :condition (and (at start (available))
                        (at start (ready_workbench)) 
                        (at start (>= (stock ?c) 0))
                        (at start (at ?loc1))
                        (at start (can_assemble ?loc1))
                        (at start (>= (stock ?w1) 72 ) ) 
                        (at start (>= (stock ?lb) 18 ) )
                        (at start (>= (stock ?i) 18 ) )
                        (at end (>= (stock ?w1) 0 ) ) 
                        (at end (>= (stock ?lb) 0 ) )
                        (at end (>= (stock ?i) 0 ) )
                        )
        :effect (and    (at start (not (available)))
                        (at start (increase (stock ?c) 9) )
                        (at start (decrease (stock ?w1) 72 ) )
                        (at start (decrease (stock ?lb) 18 ) )
                        (at start (decrease (stock ?i) 18 ) )
                        (at end (available))
        ))
                (:durative-action produce_chests12
        :parameters(?c - chest ?w1 - wood ?lb - lead_bar ?i - iron_bar ?loc1 - location)
        :duration (= ?duration 5)
        :condition (and (at start (available))
                        (at start (ready_workbench)) 
                        (at start (>= (stock ?c) 0))
                        (at start (at ?loc1))
                        (at start (can_assemble ?loc1))
                        (at start (>= (stock ?w1) 96 ) ) 
                        (at start (>= (stock ?lb) 24 ) )
                        (at start (>= (stock ?i) 24 ) )
                        (at end (>= (stock ?w1) 0 ) ) 
                        (at end (>= (stock ?lb) 0 ) )
                        (at end (>= (stock ?i) 0 ) )
                        )
        :effect (and    (at start (not (available)))
                        (at start (increase (stock ?c) 12) )
                        (at start (decrease (stock ?w1) 96 ) )
                        (at start (decrease (stock ?lb) 24 ) )
                        (at start (decrease (stock ?i) 24 ) )
                        (at end (available))
        ))
                (:durative-action produce_chests15
        :parameters(?c - chest ?w1 - wood ?lb - lead_bar ?i - iron_bar ?loc1 - location)
        :duration (= ?duration 5)
        :condition (and (at start (available))
                        (at start (ready_workbench)) 
                        (at start (>= (stock ?c) 0))
                        (at start (at ?loc1))
                        (at start (can_assemble ?loc1))
                        (at start (>= (stock ?w1) 120 ) ) 
                        (at start (>= (stock ?lb) 30 ) )
                        (at start (>= (stock ?i) 30 ) )
                        (at end (>= (stock ?w1) 0 ) ) 
                        (at end (>= (stock ?lb) 0 ) )
                        (at end (>= (stock ?i) 0 ) )
                        )
        :effect (and    (at start (not (available)))
                        (at start (increase (stock ?c) 15) )
                        (at start (decrease (stock ?w1) 120 ) )
                        (at start (decrease (stock ?lb) 30 ) )
                        (at start (decrease (stock ?i) 30 ) )
                        (at end (available))
        ))
                (:durative-action produce_chests18
        :parameters(?c - chest ?w1 - wood ?lb - lead_bar ?i - iron_bar ?loc1 - location)
        :duration (= ?duration 5)
        :condition (and (at start (available))
                        (at start (ready_workbench)) 
                        (at start (>= (stock ?c) 0))
                        (at start (at ?loc1))
                        (at start (can_assemble ?loc1))
                        (at start (>= (stock ?w1) 144 ) ) 
                        (at start (>= (stock ?lb) 36 ) )
                        (at start (>= (stock ?i) 36 ) )
                        (at end (>= (stock ?w1) 0 ) ) 
                        (at end (>= (stock ?lb) 0 ) )
                        (at end (>= (stock ?i) 0 ) )
                        )
        :effect (and    (at start (not (available)))
                        (at start (increase (stock ?c) 18) )
                        (at start (decrease (stock ?w1) 144 ) )
                        (at start (decrease (stock ?lb) 36 ) )
                        (at start (decrease (stock ?i) 36 ) )
                        (at end (available))
        ))
                (:durative-action produce_chests21
        :parameters(?c - chest ?w1 - wood ?lb - lead_bar ?i - iron_bar ?loc1 - location)
        :duration (= ?duration 5)
        :condition (and (at start (available))
                        (at start (ready_workbench)) 
                        (at start (>= (stock ?c) 0))
                        (at start (at ?loc1))
                        (at start (can_assemble ?loc1))
                        (at start (>= (stock ?w1) 168 ) ) 
                        (at start (>= (stock ?lb) 42 ) )
                        (at start (>= (stock ?i) 42 ) )
                        (at end (>= (stock ?w1) 0 ) ) 
                        (at end (>= (stock ?lb) 0 ) )
                        (at end (>= (stock ?i) 0 ) )
                        )
        :effect (and    (at start (not (available)))
                        (at start (increase (stock ?c) 21) )
                        (at start (decrease (stock ?w1) 168 ) )
                        (at start (decrease (stock ?lb) 42 ) )
                        (at start (decrease (stock ?i) 42 ) )
                        (at end (available))
        ))
                (:durative-action produce_chests24
        :parameters(?c - chest ?w1 - wood ?lb - lead_bar ?i - iron_bar ?loc1 - location)
        :duration (= ?duration 5)
        :condition (and (at start (available))
                        (at start (ready_workbench)) 
                        (at start (>= (stock ?c) 0))
                        (at start (at ?loc1))
                        (at start (can_assemble ?loc1))
                        (at start (>= (stock ?w1) 192 ) ) 
                        (at start (>= (stock ?lb) 48 ) )
                        (at start (>= (stock ?i) 48 ) )
                        (at end (>= (stock ?w1) 0 ) ) 
                        (at end (>= (stock ?lb) 0 ) )
                        (at end (>= (stock ?i) 0 ) )
                        )
        :effect (and    (at start (not (available)))
                        (at start (increase (stock ?c) 24) )
                        (at start (decrease (stock ?w1) 192 ) )
                        (at start (decrease (stock ?lb) 48 ) )
                        (at start (decrease (stock ?i) 48 ) )
                        (at end (available))
        ))
                (:durative-action produce_chests27
        :parameters(?c - chest ?w1 - wood ?lb - lead_bar ?i - iron_bar ?loc1 - location)
        :duration (= ?duration 5)
        :condition (and (at start (available))
                        (at start (ready_workbench)) 
                        (at start (>= (stock ?c) 0))
                        (at start (at ?loc1))
                        (at start (can_assemble ?loc1))
                        (at start (>= (stock ?w1) 216 ) ) 
                        (at start (>= (stock ?lb) 54 ) )
                        (at start (>= (stock ?i) 54 ) )
                        (at end (>= (stock ?w1) 0 ) ) 
                        (at end (>= (stock ?lb) 0 ) )
                        (at end (>= (stock ?i) 0 ) )
                        )
        :effect (and    (at start (not (available)))
                        (at start (increase (stock ?c) 27) )
                        (at start (decrease (stock ?w1) 216 ) )
                        (at start (decrease (stock ?lb) 54 ) )
                        (at start (decrease (stock ?i) 54 ) )
                        (at end (available))
        ))
                (:durative-action produce_chests30
        :parameters(?c - chest ?w1 - wood ?lb - lead_bar ?i - iron_bar ?loc1 - location)
        :duration (= ?duration 5)
        :condition (and (at start (available))
                        (at start (ready_workbench)) 
                        (at start (>= (stock ?c) 0))
                        (at start (at ?loc1))
                        (at start (can_assemble ?loc1))
                        (at start (>= (stock ?w1) 240 ) ) 
                        (at start (>= (stock ?lb) 60 ) )
                        (at start (>= (stock ?i) 60 ) )
                        (at end (>= (stock ?w1) 0 ) ) 
                        (at end (>= (stock ?lb) 0 ) )
                        (at end (>= (stock ?i) 0 ) )
                        )
        :effect (and    (at start (not (available)))
                        (at start (increase (stock ?c) 30) )
                        (at start (decrease (stock ?w1) 240 ) )
                        (at start (decrease (stock ?lb) 60 ) )
                        (at start (decrease (stock ?i) 60 ) )
                        (at end (available))
        ))
                
(:durative-action produce_platinum_swords3
        :parameters(?s - platinum_sword ?pb - platinum_bar ?loc1 - location)
        :duration (= ?duration 3)
        :condition (and (at start (available))
                        (at start (ready_anvil)) 
                        (at start (at ?loc1))
                        (at start (can_assemble ?loc1))
                        (at start (>= (stock ?pb) 15 ) ) 
        				(at end (>= (stock ?pb) 0 ) ) 
        				(at end (>= (stock ?s) 0 ) ) 
                        )
        :effect (and    (at start (not (available)))
                        (at start (increase (stock ?s) 3) )
                        (at start (decrease (stock ?pb) 15 ) )
                        (at end (available))
        ))
        (:durative-action produce_platinum_swords6
        :parameters(?s - platinum_sword ?pb - platinum_bar ?loc1 - location)
        :duration (= ?duration 3)
        :condition (and (at start (available))
                        (at start (ready_anvil)) 
                        (at start (at ?loc1))
                        (at start (can_assemble ?loc1))
                        (at start (>= (stock ?pb) 30 ) ) 
        				(at end (>= (stock ?pb) 0 ) ) 
        				(at end (>= (stock ?s) 0 ) ) 
                        )
        :effect (and    (at start (not (available)))
                        (at start (increase (stock ?s) 6) )
                        (at start (decrease (stock ?pb) 30 ) )
                        (at end (available))
        ))
        (:durative-action produce_platinum_swords9
        :parameters(?s - platinum_sword ?pb - platinum_bar ?loc1 - location)
        :duration (= ?duration 3)
        :condition (and (at start (available))
                        (at start (ready_anvil)) 
                        (at start (at ?loc1))
                        (at start (can_assemble ?loc1))
                        (at start (>= (stock ?pb) 45 ) ) 
        				(at end (>= (stock ?pb) 0 ) ) 
        				(at end (>= (stock ?s) 0 ) ) 
                        )
        :effect (and    (at start (not (available)))
                        (at start (increase (stock ?s) 9) )
                        (at start (decrease (stock ?pb) 45 ) )
                        (at end (available))
        ))
        (:durative-action produce_platinum_swords12
        :parameters(?s - platinum_sword ?pb - platinum_bar ?loc1 - location)
        :duration (= ?duration 3)
        :condition (and (at start (available))
                        (at start (ready_anvil)) 
                        (at start (at ?loc1))
                        (at start (can_assemble ?loc1))
                        (at start (>= (stock ?pb) 60 ) ) 
        				(at end (>= (stock ?pb) 0 ) ) 
        				(at end (>= (stock ?s) 0 ) ) 
                        )
        :effect (and    (at start (not (available)))
                        (at start (increase (stock ?s) 12) )
                        (at start (decrease (stock ?pb) 60 ) )
                        (at end (available))
        ))
        (:durative-action produce_platinum_swords15
        :parameters(?s - platinum_sword ?pb - platinum_bar ?loc1 - location)
        :duration (= ?duration 3)
        :condition (and (at start (available))
                        (at start (ready_anvil)) 
                        (at start (at ?loc1))
                        (at start (can_assemble ?loc1))
                        (at start (>= (stock ?pb) 75 ) ) 
        				(at end (>= (stock ?pb) 0 ) ) 
        				(at end (>= (stock ?s) 0 ) ) 
                        )
        :effect (and    (at start (not (available)))
                        (at start (increase (stock ?s) 15) )
                        (at start (decrease (stock ?pb) 75 ) )
                        (at end (available))
        ))
        (:durative-action produce_platinum_swords18
        :parameters(?s - platinum_sword ?pb - platinum_bar ?loc1 - location)
        :duration (= ?duration 3)
        :condition (and (at start (available))
                        (at start (ready_anvil)) 
                        (at start (at ?loc1))
                        (at start (can_assemble ?loc1))
                        (at start (>= (stock ?pb) 90 ) ) 
        				(at end (>= (stock ?pb) 0 ) ) 
        				(at end (>= (stock ?s) 0 ) ) 
                        )
        :effect (and    (at start (not (available)))
                        (at start (increase (stock ?s) 18) )
                        (at start (decrease (stock ?pb) 90 ) )
                        (at end (available))
        ))
        (:durative-action produce_platinum_swords21
        :parameters(?s - platinum_sword ?pb - platinum_bar ?loc1 - location)
        :duration (= ?duration 3)
        :condition (and (at start (available))
                        (at start (ready_anvil)) 
                        (at start (at ?loc1))
                        (at start (can_assemble ?loc1))
                        (at start (>= (stock ?pb) 105 ) ) 
        				(at end (>= (stock ?pb) 0 ) ) 
        				(at end (>= (stock ?s) 0 ) ) 
                        )
        :effect (and    (at start (not (available)))
                        (at start (increase (stock ?s) 21) )
                        (at start (decrease (stock ?pb) 105 ) )
                        (at end (available))
        ))
        (:durative-action produce_platinum_swords24
        :parameters(?s - platinum_sword ?pb - platinum_bar ?loc1 - location)
        :duration (= ?duration 3)
        :condition (and (at start (available))
                        (at start (ready_anvil)) 
                        (at start (at ?loc1))
                        (at start (can_assemble ?loc1))
                        (at start (>= (stock ?pb) 120 ) ) 
        				(at end (>= (stock ?pb) 0 ) ) 
        				(at end (>= (stock ?s) 0 ) ) 
                        )
        :effect (and    (at start (not (available)))
                        (at start (increase (stock ?s) 24) )
                        (at start (decrease (stock ?pb) 120 ) )
                        (at end (available))
        ))
        (:durative-action produce_platinum_swords27
        :parameters(?s - platinum_sword ?pb - platinum_bar ?loc1 - location)
        :duration (= ?duration 3)
        :condition (and (at start (available))
                        (at start (ready_anvil)) 
                        (at start (at ?loc1))
                        (at start (can_assemble ?loc1))
                        (at start (>= (stock ?pb) 135 ) ) 
        				(at end (>= (stock ?pb) 0 ) ) 
        				(at end (>= (stock ?s) 0 ) ) 
                        )
        :effect (and    (at start (not (available)))
                        (at start (increase (stock ?s) 27) )
                        (at start (decrease (stock ?pb) 135 ) )
                        (at end (available))
        ))
        (:durative-action produce_platinum_swords30
        :parameters(?s - platinum_sword ?pb - platinum_bar ?loc1 - location)
        :duration (= ?duration 3)
        :condition (and (at start (available))
                        (at start (ready_anvil)) 
                        (at start (at ?loc1))
                        (at start (can_assemble ?loc1))
                        (at start (>= (stock ?pb) 150 ) ) 
        				(at end (>= (stock ?pb) 0 ) ) 
        				(at end (>= (stock ?s) 0 ) ) 
                        )
        :effect (and    (at start (not (available)))
                        (at start (increase (stock ?s) 30) )
                        (at start (decrease (stock ?pb) 150 ) )
                        (at end (available))
        ))
        
(:durative-action go_to
            :parameters (?loc1 ?loc2 - location)
            :duration (>= ?duration (distance ?loc1 ?loc2) )
            :condition (and (at start (at ?loc1) )
                            (at start (link ?loc1 ?loc2) ) 
                            (at start (available)))
            :effect (and       
                        (at start (not (available)))
                        (at start (not (at ?loc1)))
                        (at end (at ?loc2))
                       (at end (available))
                    ))
            
(:durative-action place_beds
    :parameters (?b - bed)
    :duration (<= ?duration 0.5)
    :condition (and     (at start (> (stock ?b) 10) )
                        (at start (available))
                        (at end (>= (stock ?b) 0) )  
    					 )
    :effect (and        
                        (at start (not (available)))
                        (at end (placed_beds)) 
                        (at start (decrease (stock ?b) 10))
                        (at end (available)) ) )

    
(:durative-action place_chests
    :parameters (?c - chest)
    :duration (<= ?duration 0.5)
    :condition (and     
                        (at start (> (stock ?c) 10) )
                        (at start (available))
                        (at end (>= (stock ?c) 0) ) )
    :effect (and        
                        (at start (not (available)))
                        (at end (placed_chests)) 
                        (at start (decrease (stock ?c) 10))
                        (at end (available)) ) )
    
(:durative-action place_swords
    :parameters (?s - platinum_sword)
    :duration (<= ?duration 0.5)
    :condition (and     (at start (> (stock ?s) 10) )
                        (at start (available))
                        (at end (>= (stock ?s) 0) )  
    					 )
    :effect (and        
                        (at start (not (available)))
                        (at end (placed_swords)) 
                        (at start (decrease (stock ?s) 10))
                        (at end (available)) ) )
    
)