(define (problem airplane-cargo0) (:domain airplane)
(:objects
	tanker0 tanker1  - tanker
	plane0 plane1  - plane
	airport0 airport1 airport2 airport3  - airport
	refinery0 refinery1 refinery2 refinery3  - refinery
	cargo0 cargo1 cargo2 cargo3  - cargo
)

(:init
	(can_fly plane0)
	(can_fly plane1)

	(tanker_at tanker0 refinery2)
	(tanker_at tanker1 refinery0)

	(plane_at plane0 airport3)
	(plane_at plane1 airport0)

	(cargo_at cargo0 airport1)
	(cargo_at cargo1 airport1)
	(cargo_at cargo2 airport3)
	(cargo_at cargo3 airport1)

	(route airport0 airport1)
	(route airport0 airport2)
	(route airport0 airport3)
	(route airport1 airport0)
	(route airport1 airport2)
	(route airport1 airport3)
	(route airport2 airport0)
	(route airport2 airport1)
	(route airport2 airport3)
	(route airport3 airport0)
	(route airport3 airport1)
	(route airport3 airport2)

	(conn airport0 airport1)
	(conn airport0 airport2)
	(conn airport0 airport3)
	(conn airport1 airport0)
	(conn airport1 airport2)
	(conn airport1 airport3)
	(conn airport2 airport0)
	(conn airport2 airport1)
	(conn airport2 airport3)
	(conn airport3 airport0)
	(conn airport3 airport1)
	(conn airport3 airport2)

	(conn airport0 refinery0)
	(conn refinery0 airport0)
	(conn airport0 refinery1)
	(conn refinery1 airport0)
	(conn airport0 refinery2)
	(conn refinery2 airport0)
	(conn airport0 refinery3)
	(conn refinery3 airport0)
	(conn airport1 refinery0)
	(conn refinery0 airport1)
	(conn airport1 refinery1)
	(conn refinery1 airport1)
	(conn airport1 refinery2)
	(conn refinery2 airport1)
	(conn airport1 refinery3)
	(conn refinery3 airport1)
	(conn airport2 refinery0)
	(conn refinery0 airport2)
	(conn airport2 refinery1)
	(conn refinery1 airport2)
	(conn airport2 refinery2)
	(conn refinery2 airport2)
	(conn airport2 refinery3)
	(conn refinery3 airport2)
	(conn airport3 refinery0)
	(conn refinery0 airport3)
	(conn airport3 refinery1)
	(conn refinery1 airport3)
	(conn airport3 refinery2)
	(conn refinery2 airport3)
	(conn airport3 refinery3)
	(conn refinery3 airport3)

	(idle tanker0)
	(idle tanker1)
	(= (refinery_tank_level refinery0) 200000)
	(= (refinery_tank_level refinery1) 200000)
	(= (refinery_tank_level refinery2) 200000)
	(= (refinery_tank_level refinery3) 200000)

	(= (plane_tank_capacity plane0) 50000)
	(= (plane_tank_capacity plane1) 50000)

	(= (plane_tank_level plane0) 83)
	(= (plane_tank_level plane1) 97)

	(= (tanker_capacity tanker0) 25000)
	(= (tanker_capacity tanker1) 25000)

	(= (tanker_level tanker0) 67)
	(= (tanker_level tanker1) 29)

	(= (flying_distance airport0 airport1) 373)
	(= (flying_distance airport0 airport2) 502)
	(= (flying_distance airport0 airport3) 366)
	(= (flying_distance airport1 airport0) 691)
	(= (flying_distance airport1 airport2) 692)
	(= (flying_distance airport1 airport3) 345)
	(= (flying_distance airport2 airport0) 424)
	(= (flying_distance airport2 airport1) 294)
	(= (flying_distance airport2 airport3) 458)
	(= (flying_distance airport3 airport0) 608)
	(= (flying_distance airport3 airport1) 583)
	(= (flying_distance airport3 airport2) 584)
)

(:goal	(and

	(cargo_at cargo1 airport2)
	(cargo_at cargo2 airport2)
	(cargo_at cargo0 airport2)
	(cargo_at cargo3 airport3)
		)
	)
)