
(define (domain oil-transport-domain)
   (:requirements :typing :fluents :durative-actions :duration-inequalities )
  
   (:types 	tanker 
   			refinery airport - location 
            plane 
            cargo
            )
  
   (:predicates
   	(tanker_at ?tker - tanker ?loc - location)
      (plane_at ?plane - plane ?a - airport) 
      (cargo_at ?o - cargo ?a - airport)
      (cargo_in ?o - cargo ?p - plane)
      (conn ?loc1 ?loc2 - location)
      (route ?l1 ?l2 - airport)
      (idle ?tker - tanker)
      (can_fly ?p - plane)
   )

   (:functions
      (refinery_tank_level ?loc - refinery)

      (plane_tank_capacity ?p - plane)
      (plane_tank_level ?p - plane)

   	(tanker_level ?tker - tanker)
   	(tanker_capacity ?tker - tanker)

      (flying_distance ?a ?b - airport)
   )

   (:durative-action drive_tanker
      :parameters (?tker - tanker ?loc1 ?loc2 - location)
      :duration (= ?duration 50) 
      :condition (and
                  (at start (tanker_at ?tker ?loc1)) 
                  (at start (conn ?loc1 ?loc2) )  
                  (at start (idle ?tker))
               )
      :effect (and 
                  (at start (not (idle ?tker)))
                  (at start (not (tanker_at ?tker ?loc1)))
                  (at end (tanker_at ?tker ?loc2))
                  (at end  (idle ?tker) )
         )
   )
   
   (:durative-action load_airplane
   :parameters (?o - cargo ?p - plane ?loc - airport)
   :duration (= ?duration 10)
   :condition (and (at start (can_fly ?p))

                     (at start (plane_at ?p ?loc))
                     (over all (plane_at ?p ?loc)) 
                     (at end (plane_at ?p ?loc))

                     (at start (cargo_at ?o ?loc)) 
               )
   :effect (and   
                  (at start (not (can_fly ?p)))
                  (at start (not (cargo_at ?o ?loc) ) )
                  (at end (cargo_in ?o ?p) ) 
                  (at end  (can_fly ?p) )
            )
   )

(:durative-action unload_airplane
   :parameters (?o - cargo ?p - plane ?loc - airport)
   :duration (= ?duration 10)
   :condition (and 
                (at start (can_fly ?p))
               (at start (plane_at ?p ?loc)) 
               (over all (plane_at ?p ?loc)) 
               (at end (plane_at ?p ?loc))

               (at start (cargo_in ?o ?p))
               )
   :effect (and 
               (at start (not (can_fly ?p)))
               (at start (not (cargo_in ?o ?p) ) )
               (at end (cargo_at ?o ?loc) )
               (at end  (can_fly ?p) )
           
            )
)

   (:durative-action fly_airplane
   :parameters (?p - plane ?loc1 ?loc2 - airport)
   :duration (and  (>= ?duration (* (flying_distance ?loc1 ?loc2) 10 ) ) (<= ?duration 20000) 
                 ; (= ?duration 100)
      )
   :condition (and 
                  (at start (can_fly ?p))
                  (at start (route ?loc1 ?loc2))
                  (at start (plane_at ?p ?loc1)) 

                  (at start (>= (plane_tank_level ?p) (* (flying_distance ?loc1 ?loc2) 5) ) ) 
                  (over all (>= (plane_tank_level ?p) 0 ) ) 
                  (at end (>= (plane_tank_level ?p) 0) )

                  )
   :effect (and                        
                  (at start (not (can_fly ?p)))
                  (at start (not (plane_at ?p ?loc1) ) )
                  (at start (decrease (plane_tank_level ?p) (* (flying_distance ?loc1 ?loc2) 5) ) )
                  (at end (plane_at ?p ?loc2))
                  (at end  (can_fly ?p) )

                  )
)

      (:durative-action fly_airplane_fast
   :parameters (?p - plane ?loc1 ?loc2 - airport)
   :duration (and  (>= ?duration (* (flying_distance ?loc1 ?loc2) 5 ) ) (<= ?duration 20000) 
      )
   :condition (and 
                  (at start (can_fly ?p))
                  (at start (route ?loc1 ?loc2))
                  (at start (plane_at ?p ?loc1)) 

                  (at start (>= (plane_tank_level ?p) (* (flying_distance ?loc1 ?loc2) 10) ) ) 
                  (over all (>= (plane_tank_level ?p) 0 ) ) 
                  (at end (>= (plane_tank_level ?p) 0) )

                  )
   :effect (and                        
                  (at start (not (can_fly ?p)))
                  (at start (not (plane_at ?p ?loc1) ) )
                  (at start (decrease (plane_tank_level ?p) (* (flying_distance ?loc1 ?loc2) 10) ) )
                  (at end (plane_at ?p ?loc2))
                  (at end  (can_fly ?p) )

                  )
)

(:durative-action fill_airplane_tank25000
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 25000))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 25000)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 25000) )
(at end (increase (plane_tank_level ?p) 25000))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker25000
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 25000 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 25000) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 25000)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 25000) )
(at end (increase (tanker_level ?tker) 25000))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank24500
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 24500))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 24500)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 24500) )
(at end (increase (plane_tank_level ?p) 24500))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker24500
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 24500 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 24500) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 24500)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 24500) )
(at end (increase (tanker_level ?tker) 24500))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank24000
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 24000))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 24000)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 24000) )
(at end (increase (plane_tank_level ?p) 24000))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker24000
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 24000 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 24000) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 24000)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 24000) )
(at end (increase (tanker_level ?tker) 24000))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank23500
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 23500))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 23500)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 23500) )
(at end (increase (plane_tank_level ?p) 23500))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker23500
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 23500 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 23500) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 23500)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 23500) )
(at end (increase (tanker_level ?tker) 23500))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank23000
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 23000))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 23000)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 23000) )
(at end (increase (plane_tank_level ?p) 23000))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker23000
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 23000 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 23000) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 23000)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 23000) )
(at end (increase (tanker_level ?tker) 23000))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank22500
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 22500))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 22500)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 22500) )
(at end (increase (plane_tank_level ?p) 22500))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker22500
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 22500 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 22500) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 22500)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 22500) )
(at end (increase (tanker_level ?tker) 22500))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank22000
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 22000))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 22000)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 22000) )
(at end (increase (plane_tank_level ?p) 22000))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker22000
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 22000 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 22000) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 22000)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 22000) )
(at end (increase (tanker_level ?tker) 22000))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank21500
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 21500))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 21500)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 21500) )
(at end (increase (plane_tank_level ?p) 21500))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker21500
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 21500 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 21500) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 21500)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 21500) )
(at end (increase (tanker_level ?tker) 21500))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank21000
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 21000))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 21000)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 21000) )
(at end (increase (plane_tank_level ?p) 21000))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker21000
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 21000 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 21000) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 21000)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 21000) )
(at end (increase (tanker_level ?tker) 21000))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank20500
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 20500))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 20500)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 20500) )
(at end (increase (plane_tank_level ?p) 20500))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker20500
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 20500 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 20500) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 20500)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 20500) )
(at end (increase (tanker_level ?tker) 20500))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank20000
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 20000))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 20000)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 20000) )
(at end (increase (plane_tank_level ?p) 20000))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker20000
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 20000 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 20000) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 20000)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 20000) )
(at end (increase (tanker_level ?tker) 20000))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank19500
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 19500))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 19500)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 19500) )
(at end (increase (plane_tank_level ?p) 19500))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker19500
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 19500 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 19500) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 19500)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 19500) )
(at end (increase (tanker_level ?tker) 19500))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank19000
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 19000))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 19000)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 19000) )
(at end (increase (plane_tank_level ?p) 19000))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker19000
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 19000 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 19000) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 19000)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 19000) )
(at end (increase (tanker_level ?tker) 19000))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank18500
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 18500))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 18500)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 18500) )
(at end (increase (plane_tank_level ?p) 18500))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker18500
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 18500 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 18500) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 18500)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 18500) )
(at end (increase (tanker_level ?tker) 18500))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank18000
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 18000))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 18000)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 18000) )
(at end (increase (plane_tank_level ?p) 18000))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker18000
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 18000 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 18000) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 18000)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 18000) )
(at end (increase (tanker_level ?tker) 18000))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank17500
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 17500))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 17500)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 17500) )
(at end (increase (plane_tank_level ?p) 17500))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker17500
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 17500 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 17500) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 17500)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 17500) )
(at end (increase (tanker_level ?tker) 17500))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank17000
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 17000))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 17000)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 17000) )
(at end (increase (plane_tank_level ?p) 17000))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker17000
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 17000 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 17000) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 17000)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 17000) )
(at end (increase (tanker_level ?tker) 17000))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank16500
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 16500))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 16500)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 16500) )
(at end (increase (plane_tank_level ?p) 16500))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker16500
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 16500 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 16500) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 16500)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 16500) )
(at end (increase (tanker_level ?tker) 16500))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank16000
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 16000))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 16000)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 16000) )
(at end (increase (plane_tank_level ?p) 16000))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker16000
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 16000 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 16000) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 16000)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 16000) )
(at end (increase (tanker_level ?tker) 16000))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank15500
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 15500))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 15500)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 15500) )
(at end (increase (plane_tank_level ?p) 15500))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker15500
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 15500 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 15500) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 15500)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 15500) )
(at end (increase (tanker_level ?tker) 15500))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank15000
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 15000))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 15000)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 15000) )
(at end (increase (plane_tank_level ?p) 15000))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker15000
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 15000 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 15000) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 15000)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 15000) )
(at end (increase (tanker_level ?tker) 15000))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank14500
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 14500))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 14500)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 14500) )
(at end (increase (plane_tank_level ?p) 14500))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker14500
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 14500 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 14500) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 14500)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 14500) )
(at end (increase (tanker_level ?tker) 14500))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank14000
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 14000))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 14000)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 14000) )
(at end (increase (plane_tank_level ?p) 14000))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker14000
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 14000 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 14000) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 14000)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 14000) )
(at end (increase (tanker_level ?tker) 14000))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank13500
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 13500))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 13500)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 13500) )
(at end (increase (plane_tank_level ?p) 13500))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker13500
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 13500 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 13500) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 13500)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 13500) )
(at end (increase (tanker_level ?tker) 13500))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank13000
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 13000))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 13000)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 13000) )
(at end (increase (plane_tank_level ?p) 13000))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker13000
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 13000 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 13000) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 13000)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 13000) )
(at end (increase (tanker_level ?tker) 13000))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank12500
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 12500))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 12500)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 12500) )
(at end (increase (plane_tank_level ?p) 12500))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker12500
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 12500 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 12500) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 12500)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 12500) )
(at end (increase (tanker_level ?tker) 12500))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank12000
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 12000))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 12000)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 12000) )
(at end (increase (plane_tank_level ?p) 12000))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker12000
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 12000 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 12000) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 12000)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 12000) )
(at end (increase (tanker_level ?tker) 12000))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank11500
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 11500))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 11500)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 11500) )
(at end (increase (plane_tank_level ?p) 11500))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker11500
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 11500 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 11500) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 11500)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 11500) )
(at end (increase (tanker_level ?tker) 11500))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank11000
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 11000))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 11000)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 11000) )
(at end (increase (plane_tank_level ?p) 11000))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker11000
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 11000 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 11000) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 11000)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 11000) )
(at end (increase (tanker_level ?tker) 11000))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank10500
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 10500))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 10500)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 10500) )
(at end (increase (plane_tank_level ?p) 10500))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker10500
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 10500 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 10500) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 10500)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 10500) )
(at end (increase (tanker_level ?tker) 10500))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank10000
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 10000))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 10000)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 10000) )
(at end (increase (plane_tank_level ?p) 10000))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker10000
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 10000 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 10000) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 10000)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 10000) )
(at end (increase (tanker_level ?tker) 10000))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank9500
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 9500))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 9500)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 9500) )
(at end (increase (plane_tank_level ?p) 9500))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker9500
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 9500 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 9500) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 9500)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 9500) )
(at end (increase (tanker_level ?tker) 9500))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank9000
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 9000))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 9000)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 9000) )
(at end (increase (plane_tank_level ?p) 9000))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker9000
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 9000 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 9000) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 9000)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 9000) )
(at end (increase (tanker_level ?tker) 9000))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank8500
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 8500))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 8500)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 8500) )
(at end (increase (plane_tank_level ?p) 8500))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker8500
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 8500 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 8500) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 8500)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 8500) )
(at end (increase (tanker_level ?tker) 8500))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank8000
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 8000))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 8000)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 8000) )
(at end (increase (plane_tank_level ?p) 8000))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker8000
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 8000 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 8000) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 8000)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 8000) )
(at end (increase (tanker_level ?tker) 8000))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank7500
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 7500))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 7500)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 7500) )
(at end (increase (plane_tank_level ?p) 7500))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker7500
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 7500 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 7500) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 7500)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 7500) )
(at end (increase (tanker_level ?tker) 7500))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank7000
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 7000))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 7000)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 7000) )
(at end (increase (plane_tank_level ?p) 7000))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker7000
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 7000 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 7000) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 7000)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 7000) )
(at end (increase (tanker_level ?tker) 7000))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank6500
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 6500))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 6500)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 6500) )
(at end (increase (plane_tank_level ?p) 6500))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker6500
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 6500 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 6500) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 6500)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 6500) )
(at end (increase (tanker_level ?tker) 6500))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank6000
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 6000))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 6000)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 6000) )
(at end (increase (plane_tank_level ?p) 6000))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker6000
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 6000 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 6000) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 6000)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 6000) )
(at end (increase (tanker_level ?tker) 6000))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank5500
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 5500))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 5500)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 5500) )
(at end (increase (plane_tank_level ?p) 5500))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker5500
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 5500 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 5500) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 5500)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 5500) )
(at end (increase (tanker_level ?tker) 5500))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank5000
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 5000))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 5000)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 5000) )
(at end (increase (plane_tank_level ?p) 5000))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker5000
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 5000 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 5000) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 5000)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 5000) )
(at end (increase (tanker_level ?tker) 5000))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank4500
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 4500))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 4500)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 4500) )
(at end (increase (plane_tank_level ?p) 4500))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker4500
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 4500 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 4500) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 4500)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 4500) )
(at end (increase (tanker_level ?tker) 4500))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank4000
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 4000))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 4000)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 4000) )
(at end (increase (plane_tank_level ?p) 4000))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker4000
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 4000 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 4000) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 4000)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 4000) )
(at end (increase (tanker_level ?tker) 4000))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank3500
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 3500))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 3500)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 3500) )
(at end (increase (plane_tank_level ?p) 3500))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker3500
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 3500 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 3500) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 3500)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 3500) )
(at end (increase (tanker_level ?tker) 3500))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank3000
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 3000))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 3000)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 3000) )
(at end (increase (plane_tank_level ?p) 3000))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker3000
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 3000 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 3000) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 3000)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 3000) )
(at end (increase (tanker_level ?tker) 3000))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank2500
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 2500))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 2500)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 2500) )
(at end (increase (plane_tank_level ?p) 2500))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker2500
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 2500 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 2500) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 2500)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 2500) )
(at end (increase (tanker_level ?tker) 2500))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank2000
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 2000))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 2000)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 2000) )
(at end (increase (plane_tank_level ?p) 2000))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker2000
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 2000 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 2000) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 2000)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 2000) )
(at end (increase (tanker_level ?tker) 2000))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank1500
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 1500))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 1500)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 1500) )
(at end (increase (plane_tank_level ?p) 1500))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker1500
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 1500 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 1500) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 1500)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 1500) )
(at end (increase (tanker_level ?tker) 1500))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank1000
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 1000))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 1000)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 1000) )
(at end (increase (plane_tank_level ?p) 1000))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker1000
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 1000 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 1000) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 1000)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 1000) )
(at end (increase (tanker_level ?tker) 1000))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank500
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 500))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 500)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 500) )
(at end (increase (plane_tank_level ?p) 500))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker500
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 500 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 500) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 500)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 500) )
(at end (increase (tanker_level ?tker) 500))
(at end  (idle ?tker) ) ))
(:durative-action fill_airplane_tank10
:parameters (?p - plane ?tker - tanker ?airport - airport)
:duration (= ?duration 10)
:condition (and (at start (idle ?tker)) (at start (can_fly ?p))
(at start (tanker_at ?tker ?airport)) (over all (tanker_at ?tker ?airport))
(at end (tanker_at ?tker ?airport)) (at start (plane_at ?p ?airport))
(over all (plane_at ?p ?airport)) (at end (plane_at ?p ?airport))
(at start (>= (tanker_level ?tker) 10))
(at start (<= (plane_tank_level ?p) (- (plane_tank_capacity ?p) 10)))
(at end (>= (tanker_level ?tker) 0))
(at end (<= (plane_tank_level ?p) (plane_tank_capacity ?p) ) ))
:effect (and (at start (not (idle ?tker))) (at start (not (can_fly ?p)))
(at start (decrease (tanker_level ?tker) 10) )
(at end (increase (plane_tank_level ?p) 10))
(at end  (idle ?tker) ) (at end  (can_fly ?p) )))
(:durative-action fill_tanker10
:parameters (?tker - tanker ?loc - refinery)
:duration (and (>= ?duration (/ 10 1000 ) ) (<= ?duration 200) )
:condition (and (at start (idle ?tker)) (at start (tanker_at ?tker ?loc))
(over all (tanker_at ?tker ?loc)) (at end (tanker_at ?tker ?loc))
(at start (>= (refinery_tank_level ?loc) 10) )
(at start (<= (tanker_level ?tker) (- (tanker_capacity ?tker) 10)))
(at end (>= (refinery_tank_level ?loc) 0))
(at end (<= (tanker_level ?tker) (tanker_capacity ?tker)) ))
:effect (and (at start (not (idle ?tker)))
(at start (decrease (refinery_tank_level ?loc) 10) )
(at end (increase (tanker_level ?tker) 10))
(at end  (idle ?tker) ) ))
)